### ISSUE TITLE
Revisar si quan feim una Autoritzacio de Delegació s'esborren els fitxers temporals

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#110]
Revisar si quan feim una Autoritzacio de Delegació s'esborren els fitxers temporals

![imatge](https://user-images.githubusercontent.com/17084256/27534683-2b177060-5a68-11e7-8750-84e1a29fb0d0.png)

**Comment by areus-fundaciobit** [comment]
Efectivament, es crea un fitxer amb el nom `FitxerAutoritzacioDelegacio_<ID>.pdf` quan primer es crea la delegació que és la plantilla amb les variables substituides. Si després la delegació es firma correctament, aquest fitxer queda. També si s'esborra la delegació (s'hagi firmat o no) queda el fitxer.

**Comment by areus-fundaciobit** [comment]
Ara s'esborra sempre el fitxer plantilla després d'intentar la signatura. També si s'esborra la delegació i el fitxer encara existeix.
