### ISSUE TITLE
Comprovar claus repetides de Propietats Globals

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#137]
Comprovar claus repetides de Propietats Globals. S'haurà de fer via lògica i s'haurà de fer les següent comprovacions:
  * No hi pot haver propietats globals repetides
  * No hi pot haver propietats per entitat repetides dins d'una mateixa entitat
  * No hi pot haver propietats globals dins propietats per entitats (estudiar si això té sentit)

**Comment by gdeignacio-fundaciobit** [comment]
Comprovades les següents restriccions

    No hi pot haver propietats globals repetides
    No hi pot haver propietats per entitat repetides dins d'una mateixa entitat
