### ISSUE TITLE
Acursar nom de la petició en llistat de Solicitant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#147]
En les següent captures es pot observar com un nom de títol molt llarg pot fer desquadrar els llistats de peticions de firma dels usuaris Solicitant

![imatge](https://user-images.githubusercontent.com/17084256/35219165-c59d6e42-ff71-11e7-9fd3-278e71319ebf.png)

![imatge](https://user-images.githubusercontent.com/17084256/35219170-d021005e-ff71-11e7-851a-56c7b3005a77.png)

**Comment by gdeignacio-fundaciobit** [comment]
Captura del resultat

![imagen](https://user-images.githubusercontent.com/28979314/83190565-e7f12a00-a132-11ea-9699-49a4545aad06.png)

**Comment by areus-fundaciobit** [comment]
ho he provat i funciona bé. es pot tancar ja no?

**Comment by areus-fundaciobit** [comment]
S'han corregit els scripts de BDD per incloure explicitament les columnes al INSERT. No fer-ho provocava errors a qualcunes BDD que no mantenen les columnes en el mateix ordre que es definiren
