### ISSUE TITLE
Warning als logs cada vegada que es desperta el Programdor se Notificacions Callback

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#159]
Apareix el següent error al despertar-se el Programador de Notificacions callBack:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy)
on project firmasimple: Deployment failed: repository element was not specified in the POM inside 
distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help
```

No se si es que en algun lloc s'utilitza un EJB retornat des de EJBmanager.

Mirar de simplificar-unificar totes les classes encarregades de les Notificaciosn de CallBack

**Comment by anadal-fundaciobit** [comment]
El missatge està equivocat. Era un erro de ARJUNA. Amb les darreres millore ja no apareix.

**Comment by areus-fundaciobit** [comment]
Es tracta d'un BUG al JBoss 5.1.  Aquest és el tiquet https://issues.jboss.org/browse/EJBTHREE-1926
Hi ha un patch que permet solucionar-ho que es pot davallar d'aquí:

https://ejb3.jboss.org/ejb3plugin.html

Podriem documentar al manual d'instal·lació el procés d'instal·lació d'aquest plugin.
