### ISSUE TITLE
Afegir política de plugins de firma web 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#173]
Ve de #118

Afegir política de plugins de firma web dins de UsuariEntitat i dins UsuariAplicació. serà un camp "politicadepluginfirmaweb" de tipus integer amb els següents valors:
        0 - Només plugins de l'entitat
        1 - Plugins de l'entitat més plugins addicionals (afegir o llevar)
        2 - Només plugins addicionals (Només els que tenguin marcat afegir)

Ees crearan taules addicionals per guardar aquests plugins que es podran afegir o eliminar: per UsuariEntitat pfi_pluginfirmawebperusrent i per Usuari Aplicació pfi_pluginfirmawebperusrapp.

table pfi_pluginfirmawebperusrent  {
   bigint pluginfirmawebperusrentid;
   bigint usuarientitatid;
   bigint pluginfirmawebid;
   integer accio; // -1 eliminar  || 1 afegir
   UNIKE (usuarientitatid, pluginfirmawebid)
}

table pfi_pluginfirmawebperusrapp  {
   bigint pluginfirmawebperusrappid;
   bigint usuariaplicacioid;
   bigint pluginfirmawebid;
   integer accio; // -1 eliminar  || 1 afegir
   UNIKE (usuariaplicacioid, pluginfirmawebid)
}

**Comment by areus-fundaciobit** [comment]
L'estructura de base de dades ja existeix des de versions anteriors. El que mancaria seria:
 - Activar el combo de selecció dins l'edició d'usuari entitat i usuari aplicació per permetre seleccionar la política.
 - Des de la visualització dels usuaris aplicació i usuaris entitats, afegir un botó que redirigeixi al llistat de pluguins a afegir o a llevar
 - Des d'aquest llistat poder eliminar files, i un boto per crear que vagi a un formulari on es pugui seleccionar pluguin i operació (afegir o llevar)
 
D'altra banda, a la pantalla de selecció de plugins de firma consultar la política i afegir o llevar els pluguins.

**Comment by areus-fundaciobit** [comment]
Atès que dins el controlador que gestiona la firma (SignatureModuleController) cal saber quina aplicació és la que envia la firma per decidir quins plugins es poden emprar, s'havia afegit el camp applicationID a nivell de FileInfoSignature.

Però FileInfoSignature pertany a l'API dels Plugins, i no es convenient la seva modificació. Així que es guardarà un Map de <signID,applicationID > disn el PortafibSignatureSet que és exclusiu del mòdul back.

**Comment by areus-fundaciobit** [comment]
Resolt. L'id d'aplicació està a nivell de PortafibSignatureSet

**Comment by areus-fundaciobit** [comment]
Cal tenir en compte les dues polítiques definides tant a l'Usuari Aplicació i a l'Usuari Entitat.
En cas de conflicte hauria de comandar el definir a l'Usuari Persona.

**Comment by areus-fundaciobit** [comment]
Tenguent en compte que en firma asíncrona l'usuari entitat pot estar signant vàries peticons de firma d'usuaris aplicacions diferents, i per tant amb diferents peticions de firma, i que en cas de conflicte qui comanda és la configuració de l'usuari entitat, el sistema implementat per decidir els plugins que es poden mostrar és el següent:

- Si l'usuari entitat té la política "plugins d'entitat": els plugins que es mostren són els pluguins que siguin comuns de totes les aplicacions.
- Si l'usuari entitat té la política "plugins d'entitat +- plugins afegits o llevats", es mostren els plugins que siguin comuns de totes les aplicacions, a excepció d'aquells que estiguin dins la llista de llevats de l'usuari entitat, més aquells que estiguin afegits dins l'usuari entitat.
- Si l'usuari entitat té la política "només addicionals", només es mostren els plugins explicitament afegits a l'usuari entitat.
