### ISSUE TITLE
Camsp de tipus DOuble dona error no controlat al fallar el format

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#192]
Quan en un camp de Double se li posa 12,2 falla ja que requereix 12.2. El problema e´s que l'error no es agradable. Revisar codi per mostrar aquests tipus d'error millor.

![imatge](https://user-images.githubusercontent.com/17084256/46608835-57ea1100-cb06-11e8-91df-8316fd545b10.png)

**Comment by anadal-fundaciobit** [comment]
El canvis en els arxius genapp_*.properties, a part de que no s'han demanat en aquest issue han provocat que les etiquetes no es mostrin bé.
Pots tornar enrera els canvis a GenApp i PortaFIB.

 
![imatge](https://user-images.githubusercontent.com/17084256/81262556-595f2080-903e-11ea-93bf-b116c0448b02.png)

**Comment by gdeignacio-fundaciobit** [comment]
Fitxers corregits i codi regenerat.
