### ISSUE TITLE
APPLET: Emprar  applet.setStub(stub); enlloc de SignerContext

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/portafib#2]
Numero: 4
Creació: 2015-09-08 11:41:05.715000
Per poder fer test de l'applet de portafib es fa ús de una interface SignerContext quan per això la classe Applet ja proporciona un mètode anomenat setStup() que per paràmetre requereix una implementació de AppletStup.

**Comment by areus-fundaciobit** [comment]
issue obsoltea
