### ISSUE TITLE
Error: Fitxer Horitzontal A3 s'adapta a Vertical A3

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#201]
Si tenim un A3 Horitzontal, quan el passam per l'adaptador llavors es converteix en un A3 Vertical.
Revisar que podem fer, si ometre adaptació en aquests casos o revisar transformacions

[original_creat_amb_pdf24.pdf](https://github.com/GovernIB/portafib/files/2494718/original_creat_amb_pdf24.pdf)

[PeticioFirma_200505.pdf](https://github.com/GovernIB/portafib/files/2494719/PeticioFirma_200505.pdf)

**Comment by anadal-fundaciobit** [comment]
Amb aquest fitxer generat des del propi Excel 2010 no passa:

[Certificaciones prueba-1.pdf](https://github.com/GovernIB/portafib/files/2494727/Certificaciones.prueba-1.pdf)

**Comment by areus-fundaciobit** [comment]
El problema està dins el mètode forceCleanPdf de PdfUtils, que ha de mantenir la rotació. Sembla que però que la lectura de l'objecte Image sempre és sense rotació. Cal mirar més a fons com tracta la rotació la llibreria ITEXT

**Comment by areus-fundaciobit** [comment]
les pàgines poden estar girades perquè es construeixin ja així, o perquè tenen una propietat de rotació. Aquesta darrera no és tenia en compte quan es replicava el fitxer al forceCleanPdf.

Caldria revisar si a altres llocs on es manipula pdf (afegir URL de custòdia), ho fa correctament amb pàgines rotades.
