### ISSUE TITLE
No funciona Vista Completa si el nom del fitxer conté cometes simples

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#210]
Mail enviat per Pere Bauzá el dia 07/01/2019 08:44:

"Hem creat una petició de firma amb un document que conté comilles simples al nom "......CA'N ......." i aixó fa que la "Vista Completa" no funcioni."

**Comment by areus-fundaciobit** [comment]
Corregit. Mancava "escapar" el nom del fitxer i/o annexos dins els jsp.

**Comment by areus-fundaciobit** [comment]
Resolent la issue s'havia colat un error quan hi havia varis documents perquè escapva les cometes que duia cada element en javascript.
