### ISSUE TITLE
Hora inici delegació reduir a 5 minuts

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#212]
Ve de la Issue #211

2. Destinatari. Gestió de Delegats
        Actualment la “Data Inici” d’una delegació és 30 minuts + l’hora actual. Si un usuari té la necessitat de delegar en qualcú i immediatament que signe el delegat no ho podrà fer fins d’aquí 30 minuts. Igual estaria bé disminuir aquests 30 minuts a 5.
        OTAE: OK. Reduirem el temps a 5 minuts. Afegirem un missatge indicant que la delegació començarà a tenir efecte a l'hora d'inici
        DGTIC:OK

**Comment by areus-fundaciobit** [comment]
S'ha posat el temps per defecte a hora actual + 5min
S'ha detectat i corregit errada quan es creava una nova delegació i es redireccionava a pàgina per signar l'autorització mancava el paràmetre "url_user"
