### ISSUE TITLE
Ajuda a Motiu i eliminar la paraula "delegació" dels missatges de la taula de firmes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#213]
Ve del issue #211

3. Destinatari. Gestió de Delegats
        Posar una "i" de informació al camp “Motiu” on s'expliqui on sortirà el motiu i què és.
        OTAE: OK. Cap problema: si us pareix canviaré l'etiqueta “Motiu” per  “Motiu de delegació” i en l'ajuda indicaré que “Aquest motiu sortirà en la taula de firmes (si n'hi hagués) i en informació associada a la firma”.
        DGTIC:NO OK. Please, realment el que no volen és que aparegui en lloc la paraula «delegació». Ara mateix, el que surt és «Firma X per Y» (ho he configurat a les dades de l’entitat i crec que ha quedat com un grup de juristes ho volien). I després surt el Motiu. El Portafib no ha d’afegir la paraula «delegació» en lloc, ja que és justament el que no volen els juristes.
        *** Me falta passar-li a TN un missatge a posar sobre el títol «Motiu».

**Comment by areus-fundaciobit** [comment]
Ara apareix ajuda indicant que el motiu apareixerà a la taula de firmes i a la informació de la signatura. Així mateix, per eliminar la paraula delegació de la taula de signatures, el missatge per defecte diu "per substitució". Aquest missatge sempre es pot canviar modificant l'Entitat.
