### ISSUE TITLE
Millorar Log

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#220]
Ve del issue #211

12 Log (server.log)
        Millorar el log de forma que quan hi hagi una errada poguem saber a quina petició de firma correspon.
        OTAE: OK. Revisarem els logs i intentarem posar logs a l'inici i final de processos (del tipus que siguin). Ampliarem la informació en els casos d'error de firma
        DGTIC:OK

**Comment by areus-fundaciobit** [comment]
Apareixeran l'inici i el final de les operacions amb peticions de firma
