### ISSUE TITLE
Reviure la Bitacola de PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#223]
Ve del issue #211 punt 13.d

(d) Tal vegada se podria emprar “Bitacola” com eina de auditoria on tinguéssim tota la informació sobre el que ha passat a cada petició de firma arribada al PortaFIB vengui d’on vengui. A aquesta informació s’hauria d’afegir amb què mòdul/aplicació s’ha signat.
OTAE: Bitacola és una taula de BBDD de PortaFIB 1.0 que s'havia d'emprar per guardar informació relativa a les accions que passaven a certa Petició de Firma. Per falta de temps i d'oferta d'aquesta funcionalitat es va deixar aturada. Podriem retornar a primer pla l'us d'aquesta taula per fer de bitacola o log de tot el que ha passat a certa Petició. Fins i tot es podria esborrar la petició de firma i mantenir la bitacola més temps per temes d'auditories.
DGTIC:OK, però... això d’esborrar la petició de firma... se podria fer configurable?

En el issue "Ajustar BBDD per Bitàcola #234" s'haurien de fer els canvis de BBDD necessaris

**Comment by anadal-fundaciobit** [comment]
En el tiquet #234  s'ha eliminat la foreign key de Bitacola cap a Petició de Firma, d'aquesta forma es podrà esborrar la Petició de Firma i mantenir la Bitacola

**Comment by areus-fundaciobit** [comment]
Afegit missatges de bitàcola a les notificacions callback a les aplicacions

**Comment by areus-fundaciobit** [comment]
També és genera bitàcola quan Portafib avisa les aplicacions amb una notificació/callback
