### ISSUE TITLE
Que no permeti que quedi una petició de firma en estat «Firmat» sense fitxer signat.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#228]
Ve del issue #211 punt 18

18.  Que no permeti que quedi una petició de firma en estat «Firmat» sense fitxer signat.
  Darrerament hem tingut 4 casos (al CAI-1849792 n’hi ha documentats 2) on la petició de firma diu que ha estat signada OK però, no existeix ni el fitxer signat a FileSystem ni el registre corresponent a PFI_FITXER. Al menys, hauria de donar una errada a l’usuari o als logs.

**Comment by areus-fundaciobit** [comment]
S'han afegit controls en el procés de moure fitxers, per tal de que si hi ha qualsevol problema no passi desapercebut.
