### ISSUE TITLE
El bloqueig/desbloqueig massiu de notificacions no funciona

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#230]
Ve del issue #211 punt 18

21. El bloqueig/desbloqueig massiu de notificacions no funciona

Quan es selecciona un conjunt de files i s'espitja el boto desbloquejar, llavors es produeix un error javascript (informant d'un error de tipus quotes)

**Comment by anadal-fundaciobit** [comment]
El bloqueig /desbloqueig massiu només funciona quan l'estat de totes les notificacions que apareixen per pantalla és la mateixa.

**Comment by areus-fundaciobit** [comment]
S'han revisat també les redireccions. Ja que després des de bloquejar/desbloquear des del llistat anava al detall de la notificació
