### ISSUE TITLE
No funciona el filtre per dates de la pestanya de Destinatari

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#231]
Ve del issue #211 punt 22

22 No funciona el filtre per dates de la pestanya de Destinatari ja que els Databox no agafen les dates introduïdes

Te el comportament següent:
  (1) Quan el camp de filtre està buit, deixar posar la data. Si aquest dat té el format exacte dd/MM/yyyy hh:mm:ss llavors ho parseja bé. Si té un altre format recull la data actual. 
  (2) Quan el camp està ple, si s'esborra despres pareix que no es pot escriure. S'ha de fer "Cercar" de nou i es quan el camp es editable nova ment.

**Comment by areus-fundaciobit** [comment]
Actualitzada la versió de la llibreria js datetimepicker a la versió v0.0.11 des de https://tarruda.github.io/bootstrap-datetimepicker/

Al repositori https://github.com/Eonasdan/bootstrap-datetimepicker es manté una versió més evolucionada partint d'aquesta 0.0.11 però requereix adaptació del codi generat per genapp.
