### ISSUE TITLE
Ajustar BBDD per Bitàcola

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#234]
En el tiquet "Reviure la Bitacola de PortaFIB #223"  es descriu la futura funcionalitat de la Bitàcola. Revisar si la taula de BBDD s'ajusta al que es vol en el issue #223

**Comment by areus-fundaciobit** [comment]
Atès que les peticions de firma poden ser d'usuaris aplicació, els registres de la bitàcola no haurien de tenir com a camp obligatori l'usuari entitat, ja que en cas de que actui un usuari aplicació, aquest serà null
