### ISSUE TITLE
Revisar el sistema de Timer de Notificacions WS

### ISSUE THREAD

**Issue by cmiranzo-dgtic** [GovernIB/portafib#237]
Issuer #211 El Timer de Notificacions WS no funciona molt bé perquè a pesar que està configurat que s'executi cada 2 minuts, no sempre ho segueix i a vegades se reprograma per a cada 2 segons.

Substituir per un sistema de Threads.

**Comment by areus-fundaciobit** [comment]
S'ha revisat i refactoritzat el codi de notificacions.
Per clarificar el comportament: 
 - L'execució és programa cada X ms d'acord amb la propietat de configuració "notificationtimelapse". La funció principal és reintentar notificacions que hagin pogut donar errors.
 - Quan es produeix un esdeveniment (pe. firma d'una petició) que requereix una notificació, s'intenta executar el notificador tot d'una independentment de la programació.
