### ISSUE TITLE
Llistat de Fitxers per Peticio de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#246]
Afegir una pàgina d'administrador d'entitat que donat un ID de petició de Firma et mostri tots els fitxers associats a ella. 
Nota: mostrar si valen null i la ruta fisica i si existeix el fitxer fisic.

**Comment by areus-fundaciobit** [comment]
La nova pantalla és accessible a partir dels elements del llistat de peticions de firma del menú Usuari-Aplicació de l'Administrador d'Entitat
