### ISSUE TITLE
Millorar Interficie de Estadistiques

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#258]
Es tracta de millorar "Estadistiques per PortaFIB" del issue  #225

Crear un petit formulari per seleccionar rang de dates, tipus d'estadística i fitxer exportació. Al fer submit automàticament retornarà el fitxer i retornarà al formulari inicial.

A més es volen, a part de les Peticions de Firma finalitzades, el numero de firmes realitzades, ja que una petició de firmes es poden realitzar una o multiples firmes.

**Comment by areus-fundaciobit** [comment]
Ara apareix un formulari senzill per triar el rang de dates (per defecte d'inici a fi del mes anterior), si volem estadístiques per persones solicitants o per aplicacions, el tipus de peticions (inciciades, rebutjades, finalitzades), i el tipus de document (excel, ods, csv).

Apareix una opció de "estadístiques avançades" que enllaça amb l'anterior interfície.
