### ISSUE TITLE
Verificar si esta actiu un usuari aplicacio en WS 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#27]
Trac Item: 231 
Trac URL: http://trac.ibit.org/portafib/ticket/231 
Trac Creat: 03/18/14 
"Durant l'accés a un WS s'ha de comprobar que l'usuari aplicació que realitza el login no esta desactivat |Revisar en l'api de INDRA i l'API de PortaFIB i l'API REST"

**Comment by ptrias-fundaciobit** [comment]
Resolt:
![image](https://user-images.githubusercontent.com/95921330/208407347-19030aad-46b3-4918-b91c-1217d9f59bc8.png)
