### ISSUE TITLE
revisar mètode hasAccess() de PeticioDeFirmaLogicaEJB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#272]
Revisar el que s'ha fet al ISSUE: "Fer que els usuaris aplicació s'autentiquin a traves de JBoss i no emprant contrasenya de BBDD #277". Si s'ha implementat llavotrs tancar aquest ISSUE.

La implementació de hasAccess() de PeticioDeFirmaLogicaEJB ha de seguir el codi del mètode deleteFull.

Moure el xequeig de deleteFull a hasAccess() i adaptar els mètodes start, pause, .. que utilitzen hasAccess per a que rebin l'username i si se persona o aplicació.

**Comment by areus-fundaciobit** [comment]
Solucionat millorant la integració de l'apli de ws-portafirmas amb la seguretat dels EJBs. D'aquesta manera la implementació del hasAccess pot accedir al principal i als rols com amb la resta d'apis.

**Comment by areus-fundaciobit** [comment]
Sol·lucionat amb el mateix sistema que incialment s'havia provat el 12 de juny, que es emprant el "client-login", que és el que diu que s'ha d'emprar la security guide de JBoss 5.2 per fer autenticacions programàtiques. Però per qualque motiu, en el moment de processar les credencials, en la primera cridada a un EJB el loginModule de seycon no les associa correctament al thread, i aquesta falla amb un IllegalAccessException, les cridades següents funcionen correctament. S'ha previst aquest cas.
