### ISSUE TITLE
Check de disc dur a IntiServlet de BackWeb

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#275]
Afegir a la classe /portafib-back/src/main/java/es/caib/portafib/back/utils/InitServlet.java xequejos sobre el DiscDur, és a dir:
   (1) Crear un fitxer a JAVA_TEMP_DIR i esborrar-ho
   (2) Crear un fitxer a PORTAFIB_FILES_DIR i esborrar-ho
   (3) Crear un fitxer a JAVA_TEMP_DIR i fer un File.rename() a PORTAFIB_FILES_DIR

Qualsevol error ha de provocar una excepció o l'aturada del JBoss.

**Comment by areus-fundaciobit** [comment]
Comprovar també les cridades a FileSystemManager.sobreescriureFitxer que el fitxer retornat és correcte
