### ISSUE TITLE
Afegir més controls a la creació de Peticions de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#278]
L'altra dia algú va crear una Petició amb un Bloc de Firmes amb minimdefirmes igual a 0.

Afegir més revisions a la Creació de Petició (createFull):
    (1) Firmes amb numero de revisors incorrectes
    (2) Blocs amb mínim de firmes incorrectes
    (3) Blocs sense firmes
    (4) Petició sense FluxDeFirmes
   (5) ...

**Comment by areus-fundaciobit** [comment]
Els camps del fitxer a firmar tampoc és validen. S'afegeix perquè llanci una I18NValidationException i netegi si cal.

**Comment by areus-fundaciobit** [comment]
També s'afegeix validació de blocs i de firma. Problema: els camps de bloc de firma a validar que no siguin buids són tipus primitius

**Comment by areus-fundaciobit** [comment]
Cal corregir el mínim de revisors. Ara és entre 0 i el nombre total de revisors de la firma.
Ha de ser: com a mínim el nombre de revisors obligatoris i com a màxim el nombre total de revisors de la firma

**Comment by areus-fundaciobit** [comment]
El control de nombre de revisors fallava quan es creava una petició a través d'una plantilla de flux preexistent. S'ha corregit.
