### ISSUE TITLE
Eliminar Certificat de Configuració de Firma per UsuariAplicacio

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#279]
En Configuració de Firma, per temes històrics, s'ha quedat un certificat que era per quan els usuaris aplicació es volguessin autenticar emprant Certificats. Amb el redisseny de Perfils i Configuracions de Firma aquest camp ha quedat inutil i sense ús.
Eliminar-ho de la BBDD.

**Comment by areus-fundaciobit** [comment]
Està resolt ja
