### ISSUE TITLE
Revisar que Politica de Firma en Web,  API WS v1 i API Async v2

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#283]
Ve del Issue #281

Revisar que Política de Firma en:
   (1)  Web s'obtengui de les dades de l'entitat
   (2) API WS v1: S'obtengui d'entitat quan no hi hagi configuració de firma i de configuració de firma quan n'hi hagi
   (3)  API Async v2: S'obtengui de la configuració de firma

S'ha d'afegir la gestió de WS v1 en Configuració de Firmes

**Comment by areus-fundaciobit** [comment]
Ara s'agafa la política de firma de la configuració o de l'entitat.
Problema: en la firma múltiple el signatureSet té un únic commonInfoSignature. O bé s'haurà de llançar error si dues peticions no tenen la mateixa configuració de firma, o s'ha de refactoritzar perquè el filtre de certificat (i també afecta al policy), no estiguin al commonInfoSignature. És el mateix problema que el #284
