### ISSUE TITLE
Revisar d'on s'obté Filtre de Certificats en Web, API WS v1 i API Async v2

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#284]
Ve del Issue #281

Revisar d'on s'obté Filtre de Certificats en:
(1) Web s'obtengui de les dades de l'entitat
(2) API WS v1: S'obtengui d'entitat quan no hi hagi configuració de firma i de configuració de firma quan n'hi hagi
(3) API Async v2: S'obtengui de la configuració de firma

S'ha d'afegir la gestió de WS v1 en Configuració de Firmes

**Comment by areus-fundaciobit** [comment]
S'ha introduït la configuració de firma dins el commonInfoSignature  que és on s'agafa el filtre de certificats.
Problema: en la firma múltiple el signatureSet té un únic commonInfoSignature. O bé s'haurà de llançar error si dues peticions no tenen la mateixa configuració de firma, o s'ha de refactoritzar perquè el filtre de certificat (i també afecta al policy), no estiguin al commonInfoSignature
