### ISSUE TITLE
Signatura múltiple de peticions amb diferents configuració de firma

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#287]
En la firma múltiple el signatureSet té un únic commonInfoSignature. O bé s'haurà de llançar error si dues peticions no tenen la mateixa configuració de firma, o s'ha de refactoritzar perquè el filtre de certificat i el policyInfo, no estiguin al commonInfoSignature.

ve de #283 i #284

**Comment by anadal-fundaciobit** [comment]
Solució proposada:
  (1) policyInfo: passar-ho a FileInfo
  (2) filtre de certificat: obtenir el primer i tots els que no s'ajustin marcar-los amb un error i ja no processar la firma.
