### ISSUE TITLE
Error de validació amb @firma: La clave /Contents del diccionario de firma no es correcta. 

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#289]
El plugin de validació de signatures retorna el següent missatge (s'adjunta log)

La clave /Contents del diccionario de firma no es correcta. (urn:afirma:dss:1.0:profile:XSS:resultminor:PAdESInvalidContentsKey)

La firma s'ha realitzat amb el plugin d'autofirma. 
La petició no contenia taule de signatures.
La propietat de l'entitat estan fixades així : 
es.caib.portafib.transformpdfa=true
es.caib.portafib.forcecleanpdf=false

El PDF seria un PDF/A-2. 

[PAdESInvalidContentsKey.log](https://github.com/GovernIB/portafib/files/3385758/PAdESInvalidContentsKey.log)

**Comment by cmiranzo-dgtic** [comment]
Adjunt el document que signen/validen.
[G_informe provisional.pdf](https://github.com/GovernIB/portafib/files/3386187/G_informe.provisional.pdf)

**Comment by areus-fundaciobit** [comment]
El fitxers es signa correctament amb l'applet "standalone", però no des de l'aplicació. Aquests serien els paràmetres que generen un firma incorrecte

`=============================================
09:59:56,302 INFO  [MiniAppletInClientSignatureWebPlugin] ===           Applet parameters           ===
09:59:56,305 INFO  [MiniAppletInClientSignatureWebPlugin] =                                           =
09:59:56,310 INFO  [MiniAppletInClientSignatureWebPlugin] certificate_filter=
09:59:56,313 INFO  [MiniAppletInClientSignatureWebPlugin] properties_0=%23%0D%0A%23Wed+Jul+17+09%3A59%3A56+CEST+2019%0D%0AsignAlgorithm%3DSHA1withRSA%0D%0AsignType%3DAdobe+PDF%0D%0AsignReason%3DPer+petici%5Cu00F3+de+firma+directa%0D%0AsignerContact%3Dareus%40fundaciobit.org%0D%0AsignatureSubFilter%3DETSI.CAdES.detached%0D%0AalwaysCreateRevision%3Dtrue%0D%0Amode%3Dimplicit%0D%0A
09:59:56,313 INFO  [MiniAppletInClientSignatureWebPlugin] errorpage_0=http://localhost:8080/portafib/common/signmodule/requestPlugin/1563350395931058456/0/error"/>
09:59:56,314 INFO  [MiniAppletInClientSignatureWebPlugin] source_0=http://localhost:8080/portafib/common/signmodule/requestPlugin/1563350395931058456/0/source
09:59:56,314 INFO  [MiniAppletInClientSignatureWebPlugin] idname_0=G_J_anexo IyII_Informe.pdf
09:59:56,315 INFO  [MiniAppletInClientSignatureWebPlugin] destination_0=http://localhost:8080/portafib/common/signmodule/requestPlugin/1563350395931058456/0/destination
09:59:56,315 INFO  [MiniAppletInClientSignatureWebPlugin] languageUI=ca
09:59:56,316 INFO  [MiniAppletInClientSignatureWebPlugin] signAlgorithm_0=SHA1withRSA
09:59:56,316 INFO  [MiniAppletInClientSignatureWebPlugin] isjnlp=true
09:59:56,317 INFO  [MiniAppletInClientSignatureWebPlugin] signType_0=Adobe PDF
09:59:56,323 INFO  [MiniAppletInClientSignatureWebPlugin] =                                           =
09:59:56,326 INFO  [MiniAppletInClientSignatureWebPlugin] =============================================`

**Comment by areus-fundaciobit** [comment]
Sembla que la propietat que donava problemes era "alwaysCreateRevision=true"
Segons el manual de integració de @firma:

> Si se establece a true siempre crea una revisión del PDF incluso cuando el documento no contiene ninguna firma previa. **Esto requiere que los documentos de entrada cumplan estrictamente la especificación PDF 1.7 (ISO 32000-1:2008)**, y puede crear incompatibilidades con documentos PDF acordes a la especificación 1.3 creados con bibliotecas antiguas, como por ejemplo QPDF. Si se establece a false, no crea revisiones en documentos que no contengan firmas previas y sí las crea en documentos que ya contengan alguna firma.

A part del canvi al codi, cal que es deshabiliti el checkbox "Comprovar que no s´hagi modificat durant la firma" de l'Entitat, ja que el codi que fa les comprovacions detecta com a invalides signatures correctes.
