### ISSUE TITLE
Eliminació massiva dins llista de peticions de Admin. d'Entitat

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/portafib#3]
Numero: 3
Creació: 2015-08-19 07:02:36.485000
En el mètode posta list s'ha d'afegir u comptador quan entri en el if d'afegir el boto de borrat. Si estam dins l'Administrador d'Entitat llavors s'ha de comparar aquest comptador amb el tamany de la llista i si es identic llavors marca a tru la seleccio múltiple i afegir el boto de borrat multiple.

**Comment by anadal-fundaciobit** [comment]
Ja no te sentit.
