### ISSUE TITLE
Controlar perdua de sessió

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#304]
Fer que quan es perd la Sessió no mostri l'error, sinó que boto a la pàgina d'inici per tornar a carregar la sessió.

![imatge](https://user-images.githubusercontent.com/17084256/61937183-91551580-af8e-11e9-8fdf-4d11737324f7.png)

**Comment by areus-fundaciobit** [comment]
El problema estava a l'acció /canviarPipella que no formava part de la llista de URLs públiques ni de les protegides, i per tant no executava el listener d'autenticació.
