### ISSUE TITLE
Primera versió de que Usuaris externs puguin firmar  (versió per CAIB)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#309]
Ve de la ISSUE  "Usuaris externs puguin firmar #162"

Es tracta d'implementar una versió simple del ISSUE 162 per poder-la incorporar a la Carpeta Ciutadana. Com que els requeriments de la CAIb són menors, llavors començarem per una solució orientada a aquesta organització on els requeriments serien:
 (1) En CAIB, usuaris externs no existeixen (no es permeten) per lo que tot usuari (intern o extern) ha de donar-se d'alta a seycon.
(2) Enlloc d'oferir una API per a que des de una aplicació externa es puguin firmar els documents pendents de PortaFIB, s'oferira una API més simple:
            (2.a) Mètodes autenticats per usuari aplicació per obtenir les peticions de firma pendents d'un usuari persona
            (2.b) Oferir una URL d'on redireccionar a l'usuari cap a PortaFIB

**Comment by anadal-fundaciobit** [comment]
Ja he acabat una API que s'ha anomenat API Rest ExternalSignature per d'alguna forma PortaFIB i Carpeta Ciutadana puguin interactuar. Té un sol mètode que passat un idioma i una persona (username, nif o usuariadministrador) et retorna una llista de tasques pendents relacionades amb Peticions de Firma de PortaFIB.

         Adjunt un exemple d'us en Java [portafib-2.0]\ws\portafib_externalsignature_rest_jersey\src\test\java\es\caib\portafib\apisib\externalsignaturerest\api\v1\jersey\testApiExternalSignatureJerseyTester.java i un fitxer de properties amb camps d'exemple ([portafib-2.0]\ws\portafib_externalsignature_rest_jersey\apiexternalsignature.properties.sample)

         A continuació teniu la dependència maven de l'API+Connection Manager:
`
<dependency>
       <artifactId>portafib-externalsignaturerest-jersey</artifactId>
       <groupId>es.caib.portafib</groupId>
       <version>1.0.0</version>
</dependency>
`
Aquí hi ha un exemple de sortida del programa d'exemple:

`* URL ==> http://10.215.216.175:8080/portafib/
 * ========== [ROLE_SOLI] ===========
   --- [Com a Sol·licitant té peticions de firma finalitzades o rebutjades que ha de marcar com revisades] ---
    + [209143] ProvaZZZZZZZZZZZZZZZZZ(null)
    + [209221] ATTACHED(null)
    + [209205] AAA PORTS(null)
    + [207818] PDF-A2(null)
    + [207823] PDF-A2_ATTACH(null)
    + [208218] DOCUMENT TONI REUS(null)
    + [207833] PDF-A3_ATTACH(null)
    + [207828] PDF-A3(null)
    + [207694] Prova APB DICTIONAY(null)
    + [208260] PETICIO ERRONIA PDF AMB FIRMES(null)
    + [207921] PDF-A3 TAULA(null)
    + [200538] Massiu 47/50(null)
 * ========== [ROLE_DELE] ===========
   --- [Com a Delegat té peticions de firma pendents de signar] ---
    + [209076] Peticio de Firma Simple Async - 17447(null)
    + [209093] Peticio de Firma Simple Async - 17976(null)
    + [200945] Massiu 10/50(null)
    + [207813] PDF-A1 t(null)
    + [200527] Massiu 48/50(null)
    + [200868] Massiu 17/50(null)
    + [208185] Peticio de Test amb Custodia - 74616(null)
    + [206427] Peticio de Test amb Custodia - 41303(null)
 * ========== [ROLE_DEST] ===========
   --- [Com a Destinatari té peticions de firma pendents de signar] ---
    + [209076] Peticio de Firma Simple Async - 17447(null)
    + [209093] Peticio de Firma Simple Async - 17976(null)
    + [200945] Massiu 10/50(null)
    + [207813] PDF-A1 t(null)
    + [200527] Massiu 48/50(null)
    + [200868] Massiu 17/50(null)
    + [208185] Peticio de Test amb Custodia - 74616(null)
    + [206427] Peticio de Test amb Custodia - 41303(null)
`

**Comment by areus-fundaciobit** [comment]
Revisant l'autenticació REST comuna a les diferents interfícies els canvis introduïts donen problemes amb l'api simple síncrona.
