### ISSUE TITLE
Ajuntar opciones de Menu AdEn en una sola opció.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#316]
Fer un estudi de la possibilitat d'ajuntar les següent opcions de menú d'AdEn:
 * Peticions de Firma Caducades
 * Peticions de Firma d´un Destinatari
 * Neteja o Esborrat de Peticions
 * Peticions de Firma - WS v1
 * Peticions de Firma - Async Simple v2

**Comment by anadal-fundaciobit** [comment]
De les anteriors opcions de Menú estan classificades en dos grups en que cada opció depèn d'un Controllador:
 (1) AbstractPeticioDeFirmaAdenController:    Peticions de Firma Caducades,    Peticions de Firma d´un Destinatari, Neteja o Esborrat de Peticions. En aquest grup tenin dos subgrups que es classifiquen segons el tipus de filtre si és simple o complexe:
         (1.a) Peticions de Firma Caducades: Filtre complexe: ha de calcular les caducades a partir de la data actual i la data de caducitat
         (1.b) Peticions de Firma d´un Destinatari: Filtre complexe: requereix un modal per consultar sobre quin usuari volem que ens retorni totes les peticions en que ell es troba com a signant
         (1.c) Neteja o Esborrat de Peticions: Filtre Simple. Només s'elegeixen les finalitzades o rebutjades

(2) PeticioDeFirmaSoliController:  "Peticions de Firma - WS v1" i "Peticions de Firma - Async Simple v2". Aquestes dues peticions empren el mateix controlador que és el mateix que les Peticions del Sol·licitant Web, a més aquesta gestiona les peticions segon l'origen de les mateixes (Soli Web, API Async Simple v2 o API WS v1)

Pel que veig en una primera fase es podrien ajuntar en una de sola les opcions de menú:  "Peticions de Firma - WS v1", "Peticions de Firma - Async Simple v2" i "Neteja o Esborrat de Peticions", per a fer aquesta fusió s'haurien de tenir en compte les següent reflexions:
(a) La funcionalitat de "Neteja o Esborrat de Peticions" s'hauria de moure a PeticioDeFirmaSoliController. Per l'opcio d'AdEn s'hauria de demanar la raó de l'esborrat al Administrador d'Entitat.
(b) Afegir Rebutjar només per AdEn (Això ja s'ha fet al ISSUE #319)
(c) Per AdEn afegir el GroupBy pel camp Origen i la columna Origen
(d) Per AdEn mostrar el Sol·licitant Persona
(e) EN AdEn no es mostrarà descarregar Documents de les Aplicacions del Sol·licitants Web. Queda pendent que feim amb les de usuari Aplicació
(f) AdEn no pugui pausar les peticions de Firma (les podrà rebutjar) ?????
(g) Afegir les següents opcions a les Peticions de Firma d'AdEn: Flux de Firmes, Veure Fitxers i Bitacola

En uns segona fase, si la pantalla no quedes molt "saturada", es podrien anar afegint el filtratge de "Peticions de Firma Caducades"  i "Peticions de Firma d´un Destinatari"

**Comment by cmiranzo-dgtic** [comment]
No és exactament el que demanava. En realitat és el següent:

1. Que hi hagi una única opció de "Neteja i esborrat de peticions" on puguis netejar i esborrar peticions de qualsevol estat: Finalitzades, Rebutjades, En procés i No iniciades. Ni tant sols es necessita que estiguin caducades... ja ho cercarem per Dates. I que quedi registrat a la Bitàcola. Demanant la raó de l'esborrat al Administrador d'Entitat, tal com se comenta anteriorment.

2. Que hi hagi una única opció de "Peticions de firma" (de qualsevol tipus). Dins d'aquest llistat de peticions:
2.1. Jo no he demanat afegir el botó "Rebutjar" a aquest llistat. De fet, no li veig la utilitat. 
2.2. Sí s'hauria de "Per AdEn afegir el GroupBy pel camp Origen i la columna Origen"
2.3. Sí s'hauria de "Per AdEn mostrar el Sol·licitant Persona", encara que no en tenim i no està previst tindre'n (per ara). Però, en previsió de futur, està bé tindre-ho preparat.
2.4. No sé perquè com AdEn no s'han de poder descarregar documents. Aquesta funcionalitat ens ha ajudat a resoldre moltes incidències. Els administradors del servidor de correu també poden veure els correus dels usuaris.
2.5. No sé què és "pausar" una petició. I tal com comentava, no li veig la funcionalitat a rebutjar una petició.
2.6. Ok a "Afegir les següents opcions a les Peticions de Firma d'AdEn: Flux de Firmes, Veure Fitxers i Bitacola"

És a dir, amb dues llistes per separat. Per jo, el fet de tindre un procés de neteja/esborrat, és prou important com per tindre'l a un apartat diferent de la resta.

I pel que fa a "Peticions d'un destinatari", seria perfecte poder cercar a la llista de peticions també per Destinatari, però si és complicat, basta deixar-ho com està. I tampoc fa falta que hi hagi el botó "Rebutja". 

A més, a l'actual "Peticions de Firma - WS v1" hi ha un botó per eliminar. Per què? Crec que no s'hauria de poder esborrar peticions des d'aquí, sinó des de l'apartat per fer la neteja/esborrat.

**Comment by anadal-fundaciobit** [comment]
S'han centralitzat totes les pantalles de llistat de Peticions en un sol controller abstracte.
Ara sempre està disponible en AdEn l'opció d'esborrar i segons l'estat i l'origen, rebutja la petició abans d'esborrar-la.

**Comment by anadal-fundaciobit** [comment]
Millores en els llistat demanades per Cristina Miranzo:
 (1) No mostrar opció de  Llistat de peticions de Usuari Aplicació
(2) No mostrar caducades
(3) Afegir opcions de neteja (originals i adapatats) dins de llistat general
(4) No mostrar opció de menú específica de NETEJA

**Comment by anadal-fundaciobit** [comment]
Llest
