### ISSUE TITLE
Bitacola: Poder filtrar per entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#321]
COM A:  Administrador d'Entitat
VOLDRIA:  poder visualitzar les bitàcoles de Peticions de Firma de la meva Entitat
PER: auditar el sistema

Ve de Gestió general de la Bitacola #320
Ve de #325

Afegir dins de Bitacola un camp entitatID per poder filtrar en la pantalla creada en el punt #320 les entrades de certa entitat.

**Comment by areus-fundaciobit** [comment]
Resolt dins el mateix #325. Els controladors de bitàcola d'administrador entitat sempre empren com a condició addicional que l'Entitat sigui la de l'Administrador
