### ISSUE TITLE
S'han perdut les traduccions tipusestatdefirmafinal.*

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#323]
En la pantalla de vista Completa de Destinatari pareix que s'han perdut les entrades de traduccions del tipus tipusestatdefirmafinal.* tal i com es pot veure a l'imatge.

![imatge](https://user-images.githubusercontent.com/17084256/63752895-4fcbc900-c8b2-11e9-97a4-36f6f026e8b3.png)

**Comment by areus-fundaciobit** [comment]
Amb el #199 s'havia passat d'emprar nombres pels codis dels estats per les etiquetes, però mancava canviar les etiquetes d'aquesta pàgina.

**Comment by anadal-fundaciobit** [comment]
També s'han perdut aquí:

![imatge](https://user-images.githubusercontent.com/17084256/66023766-6b01a800-e4f2-11e9-9395-10d5bcb62a6d.png)

**Comment by areus-fundaciobit** [comment]
Llevades les etiquetes antigues que no feien servir número que havien quedat
