### ISSUE TITLE
Enviar Correu a tots els implicats si una petició caduca @DGMAD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#327]
Implementar una tasca nocturna que revisi totes les tasques en-proces però que estiguin caducades i enviar correu a tots els implicats d'aquella tasca (solicitant web o responsable usuari-aplicacio, destinataris, revisors, ...) indicant aquest fet i que facin alguna cosa al respecte.
Havia pensant anar enviant correus cada dos dies fins que es faci alguna cosa (es firmi o es rebutgi).

**Comment by cmiranzo-dgtic** [comment]
A nosaltres, com a CAIB, aquesta tasca no ens interessa. Si la fas només pensant en nosaltres, no ho facis please. Si ho voleu fer pensant en altres clients, tb podries afegir poder decidir com calcular la data de caducitat (ara a nosaltres ens calcula 1 mes i no sé com canviar-ho) i tb algún paràmetre per poder habilitar o deshabilitar aquest enviament, perquè el més probable és que no a tothom li interessi rebre-ho.

**Comment by anadal-fundaciobit** [comment]
Revisar ISSUE #381 i fer el que es decideixi allà.

**Comment by anadal-fundaciobit** [comment]
Es tanca ja que la DGTIC no li veu utilitat
