### ISSUE TITLE
Bitacola als canvis de configuracions dels Usuaris Aplicació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#335]
Ve de #325

Afegir les accions o canvis realitzats per un Administrador o un Administrador d'Entitat en les diferents configuracions. Estudiar la resta de llocs on es podria incloure informació de bitàcola.
Parlar amb Cristina Miranzo ja que va ser ella la que va proposar això a veure quines accions tendrien prioritat.

**Comment by areus-fundaciobit** [comment]
Es registra la creació, actualització i esborrar de configuració de firma. Tant en la creació com amb l'actualització es serialitza la informació de l'estat de la configuració de firma. A la descripció s'afegeix el nom de la configuració que fa que sigui més bona d'identificar la configuració que no amb l'id autogenerat.
