### ISSUE TITLE
Firmes CAdES i XAdES limitar-les a UNA sola firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#353]
Les firmes CAdES i XAdES incorporen dues característiques:
            (1) Firmes Attached i Detached 
            (2) Cofirmes i Contrafirmes

A causa d'això s'hauria de revisar molt millor les firmes múltiples de tipus CADES i XADES que es va implementar en els ISSUES:
          * Suportar CAdES a Firma Web, API Firma Simple Web i API Firma Simple Async #294
          * Suportar XAdES a Firma Web, API Firma Simple Web i API Firma Simple Async #333 

Un tema urgent però serà limitar els flux de firmes a  1 firma màxima.

**Comment by areus-fundaciobit** [comment]
Quan s'executa l'inici de la petició de firma, si el tipus de firma és XADES o CADES comprova que només hi hagi un bloc de firma, i que el número mínim de firmes no sigui superior a 1.
