### ISSUE TITLE
Reiniciar Peticions de Firma des d'Administrador d'Entitat no va molt be

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#368]
Reiniciar Peticions de Firma des d'Administrador d'Entitat des de l'opció "Peticions de Firma d´un Destinatari" no va molt be: Dóna un error indicant "El valor 210602 del camp Flux de Firmes està repetit (ha de ser únic)" i després els fitxers estna buits. 

![imatge](https://user-images.githubusercontent.com/17084256/66560780-5f4c5c00-eb58-11e9-9c5f-3074413c7477.png)

**Comment by areus-fundaciobit** [comment]
Intentant reproduir l'error he detectat que les consultes que es generen dins el controller de peticions d'un destinatari tarden minuts en executar-se en el cas que l'usuari sigui destinatari de moltes peticions.

**Comment by areus-fundaciobit** [comment]
Detectat també que l'operació de "reset" de petició de firma no té la corresponent operació de bitàcola, encara que sempre va associada amb un update just després

**Comment by areus-fundaciobit** [comment]
- s'ha afegit l'operació de bitàcola de resetejar que mancava
- s'han reordenat les subquerys que provocaven el retard.
- s'ha corregit l'errada (manca referència a l'atribut de sessió del formulari) i ara la reinicialització funciona com en les altres pantalles
