### ISSUE TITLE
GenApp: No pot fer sort() d'un llistat Inmodificable

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#370]
Si es té un camp de tipus Combobox i justament està buit d'elements, llavors es retorna un element EmptyKeyValues(?)  que es un List Inmutable. Quan aquest List arriba al mètode fillReferences, s'aplica un .sort() al List, però aquest al ser unmodificable llança un error.
Afegir les comprovacions oportunes abans de la cridada al sort per eviar cridar-lo si la llista és INMUTABLE.

**Comment by areus-fundaciobit** [comment]
No s'ha pogut reproduir, s'ha fet el següent test, que s'executa sense problemes:

`
List<StringKeyValue> list1 = CommonBaseController.EMPTY_STRINGKEYVALUE_LIST;
Collections.sort(list1, STRINGKEYVALUECOMPARATOR);
`

**Comment by gdeignacio-fundaciobit** [comment]
Subsanat a genapp-1.0.

**Comment by anadal-fundaciobit** [comment]
Commits a GenApp:
   - https://github.com/GovernIB/genapp/commit/c2668fa80766301f1d893f2ecf0e965c38a43e07
   - https://github.com/GovernIB/genapp/commit/c2668fa80766301f1d893f2ecf0e965c38a43e07

**Comment by anadal-fundaciobit** [comment]
(1) La solució implementada no serveix, ja que algú podria omplir la llista i després tot deixaria de funcionar. Deixar-ho com estava, i aplicar solució descrita en la primera entrada.
(2) Provar-ho amb CMAIB i PortaFIB
(3) Aplicar el canvi també a genapp 2.0
