### ISSUE TITLE
No mostra res el visor de Documents de Vista Completa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#374]
Si no tenim l'adobe acrobat o algun visor de PDFs que es pugui incrustar als navegadors, llavors la llista de documents de la Vista Completa apareix buida.

Revisar si el tag d'objecte incrustat té algun element per mostrar codi HTML quan aquest no es suporta.

Problema li va aparèixer a Felip S.

**Comment by areus-fundaciobit** [comment]
Apareixerà aquest missatge si el navegador no té la previsualització de PDFs

![imatge](https://user-images.githubusercontent.com/49397053/67200655-b2e66180-f404-11e9-835c-47c563da6e1e.png)
