### ISSUE TITLE
MotiuDeFirma i FirmatPerDelegacio no estan actius a Configuració de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#380]
Les traduccions dels camps MotiuDeFirma i FirmatPerDelegacio no estan actius a Configuració de Firma d'un Usuari Aplicació. 

(1) Fer-les actives (visibles)
(2) Aplicar on s'utilitzen que si existeixen dins  Configuració de Firma  i es tracta d'una petició amb origen APi Simple o Passarela llavors utilitzar aquest valors de Configuració de Firma
(3) Si els valors de Configuració de Firma valen null, llavors s'han d'utilitzar els valors de l'Entitat

**Comment by areus-fundaciobit** [comment]
Els camps actualment sí que estan actius però dependnets de la política de taula de firmes.

En el cas del "firmat per", només s'empra dins la generació de rúbrica visible dins PDF que ara mateix només funciona amb Taula de firmes.

**Comment by areus-fundaciobit** [comment]
El camp firmat per va lligat a la taula de firmes, i s'empra amb les apis que empren la configuració de taula de firmes: les apis síncrones i la api asincrona V2 (REST).

El camp "motiu de delegació", s'ha deslligat de la taula de firmes, ja que també s'empra per generar el "reason" de la firma encara que no hi hagi taula. Només s'empra a les firmes asincrones (les que tenen delegació), de l'API V1 i l'API V2.
