### ISSUE TITLE
Error en comparació fitxer original i signat en firmes XADES

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#384]
A traves de l'API Firma Simple (sincrona) vaig intentar fer una firma XADES i em va llançar aquest error:
-----------
 STATUS = -1 (STATUS_ERROR)
  RESULT: Error en la firma: Pareix ser que el document adjunt en la firna XAdES Attached NO es igual al document original enviat
------------

Veure que pot estar passant

**Comment by areus-fundaciobit** [comment]
realitzades proves amb Xades Atached/Detached i formats de fitxer binary i xml, l'error és ciscumscriu a: firma de fitxers xml amb format xades attached.
