### ISSUE TITLE
Revisar com es que de vegades el NIF no es troba des de API REST V2 @DGMAD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#392]
L'error és:

[es.caib.portafib.back.controller.rest.apifirmaasyncsimple.v2.RestApiFirmaAsyncSimpleV2Controller] (http-10.215.9.173-18080-6) No existeix cap usuari amb NIF 43101739S
org.fundaciobit.genapp.common.i18n.I18NException: genapp.comodi

**Comment by areus-fundaciobit** [comment]
No s'ha pogut reproduir la issue. Sembla que l'errada és limitava a un problema preexistent a la instal·lació de 2.0.1 on determinats usuaris estaven marcats com a usuaris externs. 

Atès que al a versió 2.0.1 aquest booleà no s'emprava, el problema sorgeix en actualitzar de versió. Però una vegada fet l'UPDATE per marcar els usuaris com a interns no es torna reproduir.

Segurament l'error venia de l'actualització de 1.1.x a 2.0.0, on es va introduir aquest camp d'usuari extern, i no s'actualitzes correctament aquest camp, o hi hagués un impàs en que l'agent o el formulari de modificacío no guardés correctament el nou camp.
