### ISSUE TITLE
Error al connectar-se a PortaFIB a traves de Passarela

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#408]
Dóna el següent errors: Error en createPeticioDeFirma(): perfil.passarela.nomesunperfil (org.fundaciobit.genapp.common.i18n.I18NException: perfil.passarela.nomesunperfil)

[log_ripea_portafib_un_perfil.log](https://github.com/GovernIB/portafib/files/4218932/log_ripea_portafib_un_perfil.log)

**Comment by areus-fundaciobit** [comment]
Des de la DGMAD s'ha actualitzat de la 2.0.3 a la 2.0.6 i ja no dona cap error
