### ISSUE TITLE
Fer que un destinatari rebi correu quan revisor accepti

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#413]
Quan una firma té un revisor, en el moment de l'activació del bloc de firmes que conté aquella firma, llavors ja s'envia un correu al destinatari indicant-li que te un firma pendent, quan realment no es del tot cert, ja que fins que el revisor no accepti la firma, el destinatari no podrà fer res.

Revisar aquest funcionament per veure si es pot millorar i enviar el correu del destinatari quan el revisor accepti la firma.

**Comment by ptrias-fundaciobit** [comment]
Ja estava corregit, petites millores
