### ISSUE TITLE
El número d'avisos quan hi ha notificacions bloquejades apareix a Admin Entitat enlloc de Admin d'Aplicacions

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#418]
Quan hi ha notificacions bloquejades, apareixien en el número d'avisos de la pipella de l'administrador d'entitat.

D'ençà que es va separar el menú en administrador d'aplicacions i administrador d'entitats, l'opció de veure la llista de notificacions pendents està a l'administrador d'aplicacions, però el número d'avisos segueix apareguent a la pipella d'administrador entitat enlloc de a la d'administració d'aplicacions.

![imatge](https://user-images.githubusercontent.com/49397053/77153540-37afd700-6a9a-11ea-8546-0a0211cc9cff.png)

**Comment by anadal-fundaciobit** [comment]
![imatge](https://user-images.githubusercontent.com/17084256/79950594-9a203c80-8477-11ea-9017-b90c7d64e78b.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat
