### ISSUE TITLE
Permetre afegir usuaris externs al sol·lictant

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#420]
Per permetre que des del sol·licitant és puguin crear peticions de firma amb usuaris externs es necessari qualque tipus d'opció per crear-los, ja que ara només és pot fer via API.

Es tractaria del següent, una opció de "Afegir usuari extern"
      (1) Demanaria NIF
      (2) Si existeix llavors donaria l'opció d'editar nom i email
      (3) Si no existeix llavors mostraria l'opció de crear-ho

**Comment by anadal-fundaciobit** [comment]
Fet el més important. Ja és funcional. FALTA:
     (a) Provar-ho en un flux d'una petició
     (b) Documentar-ho
     (c) Enviar mail a DGMAD (no se si fer un video ...)

**Comment by anadal-fundaciobit** [comment]
Solucionat !!!

**Comment by anadal-fundaciobit** [comment]
La creació de Peticions no funcionava si la primera firma era un usuari extern ja existent
