### ISSUE TITLE
La compilació per defecte no carrega l'ear

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#421]
Quan es compila emprant compile.bat sense cap Profile  afegit llavors JBoss 5 no carrega bé l'ear. Revisar que està passant

**Comment by areus-fundaciobit** [comment]
Sembla que el problema està en els mòduls de callback. A pesar de que en principi els perfils per incloure el mòduls de prova de callback no estan inclosos dins el compile.bat/compile.sh es generen tots els WAR

**Comment by areus-fundaciobit** [comment]
El problema era degut a fer compilacions seguides, activant i desactivant profiles. El maven-ear-plugin no és capaç de detectar els mòduls que són d'una compilació i els que són d'una anterior, i sempre els inclou a tots.

Sol·lucionat forçant sempre un `clean` només del mòdul EAR.
