### ISSUE TITLE
Error quan nom de l'arxiu de pfi_fitxer conté caràcters especials

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#425]
Des de l'IBSALUT ens comenten que quan el nom de l'arxiu conteu un caràcter especial, la descarrega del documetn falla: per exemple un caracter ´.
 Revisar si el nom s'ha de codificar durant la descarrega: 

[Sat Apr 04 11:56:10.720736 2020] [http:error] [pid 50939] [client 88.11.9.13:50737] AH02430: Response header 'Content-Disposition' value of 'inline; filename="Informe revisio\x01 factura CMA (1)_Firmat.pdf"' contains invalid characters, aborting request, referer: https://portafirmes.ssib.es/portafib/common/autofirma/final/1585994064110705180

**Comment by areus-fundaciobit** [comment]
adjunt comentari enviat a IBSalut

> Per una banda, Portafib en general funciona amb UTF-8, i és possible pujar qualsevol text, o nom de fitxer que estigui en UTF-8, i es guarda correctament.
>  
> En les descàrregues de fitxer s'empra la capçalera estàndard HTTP "Content-Disposition" on li permet indicar un nom suggerit al navegador per la descàrrega. Per estàndard, les capçaleres HTTP han d'estar codificades en ISO-8859-1.
>  
> El problema sorgeix quan es puja un nom de fitxer que té un caràcter UTF-8 que no està dins ISO-8859-1. Per exemple, passaria si ficàssim un nom de fitxer amb caràcters xinesos o ciríl·lics. Portafib llegiria bé el nom en xinés del fitxer, el guardaria correctament a la base de dades, però a l'hora de la descàrrega el nom suggerit al navegador per guardar, atès que la capçalera només pot dur caràcters ISO-8859-1, sortiria amb caràcters estranys, que el navegador no reconeix i substitueix per "_"
>  
> En el vostre cas, sembla que es tractatria d'un fitxer creat dins un MacOS. El sistema de fitxers del MacOS es veu que per guardar les lletres accentuades, enlloc d'emprar la forma més estàndard, que és directament el codi de la lletra accentuada, empra un altre sistema, que és amb la lletra més el caràcter d'accent combinat. Aquesta forma és vàlida en Unicode i es pot representar amb UTF-8, però no és compatible amb ISO-8859-1. D'aquí que quan el JBoss envia la capçalera HTTP del filename, i l'ha de codificar en ISO-8859-1 genera un caràcter estrany que fa petar l'Apache (Sense Apache davant, no dona cap error, la descàrrega va bé, només que el navegador fica un "_" al lloc del caràcter no reconegut).
>  
> Mirarem de filtrar dins la capçalera Content-Disposition els caràcters no compatibles amb ISO-8859-1 substituint-los directament per qualque comodí.
>  
> De moment, per evitar aquest tipus d'error, al marge de poder modificar el nom de fitxer dins PFI_FITXER, indicaria als usuaris que empren MacOS que evitin crear noms de fitxer amb accents o dièresis.

**Comment by areus-fundaciobit** [comment]
S'afegeix un mètode d'utilitat per crear la capçalera Content-Disposition seguint l'especificació  [RFC6266](https://tools.ietf.org/html/rfc6266). 

Bàsicament ficam un "filename=" clàssic, prèviament filtrat per evitar que hi hagi caràcters no compatibles amb ISO-8859-1, seguit d'un "filename*=UTF-8''" que permet codificar el nom escapant els caràcters, i està soportat per IE >= 9, així com Firefox i Chrome.
