### ISSUE TITLE
Tancar Versió

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#431]
Tancar Versió:
    * Fer pull
    * Revisar changes.log
    * Revisar manual de Migració
    * Regenerar scripts BDD si cal
    * Compilar i provar
    * Actualitzar portafib2.fundaciobit.org
    * Fer Deploy
    * Fer Release
    * Afegir aquest ISSUE a la propera versió (NOVA_VERSIO + 1) a TODO
    * Anar a project, edit i marcar el project com CLOSED.
    * Tancar aquest ISSUE per aquesta versió tancada

**Comment by acuevas-dgtic** [comment]
¿Se puede cerrar esta tarea y el proyecto?

**Comment by anadal-fundaciobit** [comment]
Hem de tancar protafib-2.0
