### ISSUE TITLE
Obrir Versió

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#432]
* executar novaversio.bat <NOVA_VERSIO>
* Canviar versió de versio.txt
* Editar el pom.xml i editar el tag <portafib.version> amb la nova versió.
* Esborrar les dependències de la versio anterior del .m2 i recompilar
* Crear Project de propera versió (NOVA_VERSIO + 1)
* Afegir aquest ISSUE a la propera versió (NOVA_VERSIO + 1) a TODO
* Tancar aquest ISSUE per aquesta nova versió

**Comment by areus-fundaciobit** [comment]
tanc, perquè veig que ja està fet

**Comment by anadal-fundaciobit** [comment]
Hem de tancar portafib-2.0
