### ISSUE TITLE
Afegir Profile per generar BACK amb "ClientCert"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#435]
Crear un profile que quan estigui actiu, enlloc de posar al WEB.XML autenticació BASIC, posi CLIENT-CERT

![imatge](https://user-images.githubusercontent.com/17084256/82213665-d8910600-9914-11ea-84f5-63649cbd2578.png)

**Comment by areus-fundaciobit** [comment]
S'ha modificat el plugin WAR dins el back/ perquè filtri el web.xml, i s'ha afegit el profile `back-client-cert` per emprar CLIENT-CERT enlloc del valor per defecte que s'ha deixat a BASIC.

Per tant, compilant amb "mvn .... -Pback-client-cert ..." es generarà el web.xml indicat a l'enunciat.

**Comment by areus-fundaciobit** [comment]
La versió del maven-war-plugin que s'emprava dins el back, 3.1.0, tenia un bug que feia que quan s'activava el filtre del descriptor web.xml és filtrassin els binaris de dins el WAR i fallàs el deployment. 

https://issues.apache.org/jira/browse/MWAR-407

S'ha actualitzat a la versió 3.2.3
