### ISSUE TITLE
Errada al menú d'adminstrador entitat: "Modificar dades de Persona" / "Alta de Persones"

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#438]
Quan es pitgen les opcions de "Modificar dades de Persona" o "Alta de Persones" al menú d'Administrador d'Entitat, ambos es posen en negreta, quan només hauria de ser el que s'ha seleccionat.

**Comment by gdeignacio-fundaciobit** [comment]
![imagen](https://user-images.githubusercontent.com/28979314/83655221-70058280-a5be-11ea-96d0-ae3d32a57a34.png)

![imagen](https://user-images.githubusercontent.com/28979314/83655303-8c092400-a5be-11ea-8715-18d2091c9d32.png)
