### ISSUE TITLE
Moure l'opció "Llistat Firmes Externes" del menú Administrador Entitat

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#440]
Moure aquesta opció de menú perquè estigui dins el bloc que fa referència a peticions de firma enlloc de dins el bloc d'usuaris.

**Comment by gdeignacio-fundaciobit** [comment]
Menu reordenat

![imagen](https://user-images.githubusercontent.com/28979314/83731220-717c8c80-a64a-11ea-919f-a4b478f99fdf.png)
