### ISSUE TITLE
Ús incorrecte de SimpleDateFormat

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#443]
hem detectat un parell de llocs que s'empra una instància static de SimpleDateFormat.
SimpleDateFormat no és thread-safe i no es pot reusar com static. 

 - GestioNoficiacionsWSController
 - PeticioDeFirmaLogicaEJB
 - AbstractTimerEJB

No són llocs crítics perquè només s'empra per logs o per imprimir en pantalla.

**Comment by gdeignacio-fundaciobit** [comment]
Revisats els fitxers on es s'empra static son definitivament
    
    GestioNoficiacionsWSController
    PeticioDeFirmaLogicaEJB
    AbstractTimerEJB
    
i per tests
    PortafirmasIndraTest
