### ISSUE TITLE
Errors a la pantalla de creació d'usuari entitat

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#448]
Ens reporten aquests errors a la pantalla de creació de l'usuari entitat:

>  1) Este ya hace tiempo que sale (estaba en PF 1), al seleccionar que no hay custodia sale un mensaje de "Id desconocido". No parece afectar al funcionamiento.
> 
> 2) En la lista de opciones de custodía, salen dos ítems de "Sense custòdia o la Política definida dins l'Entitat (Per defecte NO Actiu)". Me da que una opción debería decir "SÍ".
> 
![_20200521_PortaFIB_CustodiaDuplicada](https://user-images.githubusercontent.com/49397053/82652985-d41f6280-9c1e-11ea-9044-ffd46c14e1df.png)
![_20200521_PortaFIB_NoCallback](https://user-images.githubusercontent.com/49397053/82652987-d4b7f900-9c1e-11ea-9c68-46dd86154694.png)

**Comment by gdeignacio-fundaciobit** [comment]
Provada la funcionalitat, les constants estàn ben definides i no es produeixen errors.

```
// L'usuari entitat té les 3 absolutes més 3 que depene de l'entitat
  public static final int[] POLITICA_CUSTODIA_USUARI_ENTITAT = new int[] {
    // Absolutes
    ConstantsV2.POLITICA_CUSTODIA_NO_PERMETRE,
    ConstantsV2.POLITICA_CUSTODIA_OBLIGATORI_PLANTILLA_DEFINIDA_A_CONTINUACIO,
    ConstantsV2.POLITICA_CUSTODIA_LLIBERTAT_TOTAL,
    // Dependents de l'entitat.
    ConstantsV2.POLITICA_CUSTODIA_POLITICA_DE_CUSTODIA_DEFINIDA_EN_ENTITAT,
    ConstantsV2.POLITICA_CUSTODIA_SENSE_CUSTODIA_O_POLITICA_DEFINIDA_EN_ENTITAT_PER_DEFECTE_ACTIU,
    ConstantsV2.POLITICA_CUSTODIA_SENSE_CUSTODIA_O_POLITICA_DEFINIDA_EN_ENTITAT_PER_DEFECTE_NO_ACTIU
  };
```
