### ISSUE TITLE
Afegir el id a llistat de plantilles de fluxos de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#459]
S'ha d'afegir el identificador del flux de plantilla de firma al llistat i a la finestra de 'Modificar Plantilla de Flux de Firmes" (camp no editable). La visualització d'aquest identificador facilita la configuració a aplicacions externes.

**Comment by areus-fundaciobit** [comment]
L'id apareix ara al llistat
