### ISSUE TITLE
Revisió de l'estructura de directoris i mòduls Maven

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#470]
Depèn de PROJECT

La nomenclatura dels mòduls Maven no compleix amb els estàndards de desenvolupament del GOIB. S'ha de revistar l'estructura de directoris i mòduls segons l'estàndard publicat a  http://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI308670&id=308670 (pàgs 10-14)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
