### ISSUE TITLE
Destinatari: Poder revisar amb vista completa totes les firmes pendents

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#480]
En aquest moment quan un destinatari vol revisar el que ha de signar, llavors ha d'anar una a una, a la vista completa de les peticions i firmar o rebutjar, quan el que li interessaria és fer una repassada del que ha de firmar i finalment firmar-ho tot.

Es proposa un tipus de cistella que el que es compren són Peticions a Revisar/Firmar:
         (1) És seleccionarien (checkbox) totes les peticions que **en principi** es volen revisar per signar/rebutjar pel destinatari
         (2) S'espitjaria un nou boto anomenat per exemple "REVISIÓ i FIRMA/REBUIG" (Canviar el nom)
         (3) Totes les peticions seleccionades es ficarien dins una llistat en la sessió HTTP i es botaria a la "vista completa" de la petició de firma del primer element de la llista.
        (4) En la vista completa, com que venim de "REVISIÓ i FIRMA" apareixerien nous botons:  <AFEGIR PER FIRMAR i SEGÜENT>,<AFEGIR PER REBUTJAR i SEGÜENT> i <IGNORAR I SEGÜENT>. Els botons "Firmar" i "Rebutjar" desapareixerien. Si s'espitjàs  <AFEGIR PER REBUTJAR i SEGÜENT>, abans de passar al següent es mostraria un diàleg demanant la raó del rebuig.
        (5 ) Quan arribéssim al darrer element de la llista, llavors només apareixerien dos botons:
                 (a)  <APLICAR SELECCIONS ELEGIDES> que botaria directament a un procés de Rebuig múltiple i Firma Múltiple i 
                 (b)  <CANCEL·LAR>

Crec que pot ser un sistema pràctic pels alts càrrecs que revisen o que volen revisar exactament el que firmen.

**Comment by areus-fundaciobit** [comment]
Caldria afegir un resum al final indicant el resultat de peticions ignorades, rebutjades i signades
