### ISSUE TITLE
Modificar manual de instal·lació: Canvi de versió de JDK per compilar

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#483]
S'ha de canviar del manual de instal·lació la versió requerida per per compilar. Ara requereix la versió JDK 1.7. Encara es pot executar amb la versió 1.6.

**Comment by areus-fundaciobit** [comment]
Afegit JDK 7 com a requisit mínim per compilar. També s'ha inclòs la referència al nou profile definit a #435
