### ISSUE TITLE
Afegir Llegenda de Colors als Flux de Firmes 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#49]
Trac Item: 221 
Trac URL: http://trac.ibit.org/portafib/ticket/221 
Trac Creat: 03/05/14
Les firmes i blocs d'un flux de firmes en marxa van canviant el color de fons mentres el proces de firma va avançant. No existeix cap llegenda per mostrar que signifique els colors.

**Comment by areus-fundaciobit** [comment]
Tenir en compte #518

**Comment by anadal-fundaciobit** [comment]
Ja està solucionat.
