### ISSUE TITLE
Error al enviar una peticio de firma via REST v2 a un usrapp amb logo

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#498]
Es produeix un error quan es crida a crer un peticio de Firma via Api Firma Async Simple v2 (Rest) emprant un usuari aplicació que conté un logo. Adjunt el tros de codi on falla. Pareix que l'error es produeix quan intenta clonar el logo de l'usr-app per copiar-ho a la Petició.  Revisar que és el que es fa malament.

![imatge](https://user-images.githubusercontent.com/17084256/95421667-2945e180-093e-11eb-9187-03015abc603f.png)

**Comment by areus-fundaciobit** [comment]
No es pot reaprofitar el mateix objecte carregat de hibernate just fixat l'id a 0, perquè l'objecte FitxerId manté totes les relacions i es fa un taco. Enlloc d'això, simplement fent una còpia, ja està.
