### ISSUE TITLE
Actualitzar el plugin FIRe a la 2.3

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#506]
API FirmaWeb utiliza la versión de FIRe 2.1. Sha d'actualitzar a la versió 2.3 i verificar que el servei està disponible

**Comment by areus-fundaciobit** [comment]
- s'han fet les adaptacions necessàries al plugin
- s'ha actualitzat la documentació del Manual d'Usuari referent a la instal·lació del plugin (4.10.2.6)
- s'ha actualitzat la guia d'instal·lació de la demo de FIRe (pluginsib-sigantureweb/fire/doc/ )
