### ISSUE TITLE
Visualitzar firmes prèvies en la vista preliminar

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#513]
Si s'envia un document signat a portafib, s'hauria de poder visualitzar les firmes prèvies del document a l'esquerra del visor

**Comment by areus-fundaciobit** [comment]
podria anar bé així?

![imatge](https://user-images.githubusercontent.com/49397053/106277632-bab4c880-6239-11eb-9e8b-a2e8101275af.png)

**Comment by acuevas-dgtic** [comment]
De cara al usuario serie deseable destacar el contenido del common name  (CN), la fecha y la hora. El resto de información podría aparecer más pequeño, entre paréntesis,...
