### ISSUE TITLE
Revisar obligatorietat del camp "Callback URL"

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#520]
En la finestra de creació o modificació d'usuaris d'aplicació, el camp "Callback URL" no hauria de ser obligatori si es selecciona el valor "No Callback" dins del desplegable "Callback versió". A més, quan selecciones ""No Callback" apareix una finestra d'error de versió desconeguda.

![imatge](https://user-images.githubusercontent.com/58417501/106253548-e9ba4280-6217-11eb-939c-c1e2ab770edc.png)

**Comment by areus-fundaciobit** [comment]
- S'ha afegit script sql per eliminar constraint not null sobre el camp, i adaptat el codi.
- S'ha afegit una validació per comprovar que el camp només pot ser null quan s'indica a callback versió que no hi ha callback
- S'ha corregit el javascript que comprovava el camp callback versió i que no tenia en compte quan es triava "no callback"
