### ISSUE TITLE
La informació addicional de la peticó es carrega innecessàriament dins la llista de peticions pendents

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#544]
Al mètode `postList` de `AbstractEstatDeFirmaDestDeleColaController` es fa una consulta per obtenir el camp `INFORMACIOADDICIONALAVALUABLE` de la petició de firma, quan aquest es podria extreure de `peticionsByEstat` que ja s'ha carregat prèviament

**Comment by gdeignacio-fundaciobit** [comment]
Eliminada la consulta al Ejb.
Creat un Map mapInfo amb la clau de l'estat de firma i el camp informacio addicional avaluable
Carregam el contingut al valueMap del AdditionalField.
