### ISSUE TITLE
APiFirmaSimple en Servidor no retorna informació de Validació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#581]
Dins DigitalIb estic utilitzant l'API de Firma Simple en Servidor. En principi tot funciona però no retona informació de Validació. En el cas de PortaFIb hauria de retornar true o false i el que retorna és NULL.

FirmaSimpleSignedFileInfo sfi = fullResults.getSignedFileInfo();

![imagen](https://user-images.githubusercontent.com/17084256/116869919-e74df700-ac11-11eb-98d2-7014f72aa618.png)

![imagen](https://user-images.githubusercontent.com/17084256/116870033-0f3d5a80-ac12-11eb-833a-3203650ac064.png)

**Comment by areus-fundaciobit** [comment]
En principi sembla que el comportament seria el següent:
 - `null` quan la validació no està activada a la configuració de firma
 - `true` quan està activada i s'ha pogut realitzar
 - `false` quan està activada i no s'ha pogut realitzar
