### ISSUE TITLE
ApiFirma Simple en Servidor Rest retorna Perfil de Firma null

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#594]
Estam provant l'ApiFirma Simple en Servidor Rest des de DigitalIB i ens em adonat que a causa d'un error al Arxivar, resulta que retorna Perfil de Firma a null.

PS: Avisar a @anadal-fundaciobit  quan es solucioni per a que llevi el parxe de DigitalIB (https://github.com/GovernIB/digitalib/issues/140)

![imagen](https://user-images.githubusercontent.com/17084256/119813637-d1b6af00-bee9-11eb-906e-10b96a169afe.png)

![imagen](https://user-images.githubusercontent.com/17084256/119813661-d713f980-bee9-11eb-9ec9-270ba7c32a5c.png)

**Comment by areus-fundaciobit** [comment]
Acutalment veig que aquest format només s'emplena si es valida la firma, ja que la informació l'agafa del `ValidateSignatureResponse`, d'altre banda, en principi sembla que no està implementat enlloc determinar el profile. 
Caldrà veure com implementar-ho si es necessari el profile sense validar la firma. La program per la 2.0.21

**Comment by areus-fundaciobit** [comment]
Ara mateix PortaFIB només pot retornar aquests camps si la validació està activa. Dins la resposta de l'api dins el FirmaSimpleSignedFileInfo, hi ha el FirmaSimpleValidationInfo, que te el camp checkValidationSignature per si s'ha validat la firma. Per tant el clients poden saber si s'ha fet la validació, i per tant is el perfil de firma hauria d'estar ple o no.
S'ha creat la issue #669 per estudiar si s'ha de canviar aquest comportament.
