### ISSUE TITLE
API Firma Simple en Servidor no retorna els perfils ENI esperats

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#595]
En la documentació de API Firma Simple en Servidor, concretament en la classe [PORTAFIB]/apifirmasimple-api/src/main/java/org/fundaciobit/apisib/apifirmasimple/v1/beans/FirmaSimpleSignedFileInfo.java apareix que els tipus de perfil de firma són els que apareixen a la captura següent, però pareix que enlloc del que diu, retorna els tipus descrits en l'API de Validació de Firmes (veure final d'aquesta entrada).
Ho hem descobert dins de digitalIB ja intenta fer la conversió de tipus de perfil descrits dins de [pluginsib-core]src/main/java/org/fundaciobit/pluginsib/core/utils/MetadataConstants.java (veure constants ENI_PERFIL_FIRMA),

Hi ha dues solucions:
(a) S'actualitza la documentació del camp FirmaSimpleSignedFileInfo eniPerfilFirma i s'inclouen dins de la classe els perfil de més abaix (els de l'API DE VALIDACIO DE FIRMES)
(b) Es fa una conversió de PERFIL de API DE VALIDACIO DE FIRMA a valors de la constant ENI_PERFIL_FIRMA de [pluginsib-core]src/main/java/org/fundaciobit/pluginsib/core/utils/MetadataConstants.java

Per favor, consultar quina es tria amb @anadal-fundaciobit  ja que afecta de DigitalIB.

![imagen](https://user-images.githubusercontent.com/17084256/119821456-df246700-bef2-11eb-9ef3-6a1eb10afb31.png)

PERFILS DE  L'API de Validació de Firmes

  public static final String SIGNPROFILE_BES = "AdES-BES";
  public static final String SIGNPROFILE_EPES = "AdES-EPES";
  public static final String SIGNPROFILE_T = "AdES-T";
  public static final String SIGNPROFILE_C = "AdES-C";
  public static final String SIGNPROFILE_X = "AdES-X";
  public static final String SIGNPROFILE_X1 = "AdES-X1";
  public static final String SIGNPROFILE_X2 = "AdES-X2";
  public static final String SIGNPROFILE_XL = "AdES-XL";
  public static final String SIGNPROFILE_XL1 = "AdES-XL1";
  public static final String SIGNPROFILE_XL2 = "AdES-XL2";
  public static final String SIGNPROFILE_A = "AdES-A";
  public static final String SIGNPROFILE_PADES_LTV = "PAdES-LTV";
  public static final String SIGNPROFILE_PADES_BASIC = "PAdES-Basic";

**Comment by areus-fundaciobit** [comment]
després de parlar-ho amb @anadal-fundaciobit, s'ha optat per l'opció a). S'afegeixen les constants a la classe i s'actualitza la documentació
