### ISSUE TITLE
Deshabilitar chunking en les peticions a afirma

### ISSUE THREAD

**Issue by antonireus** [GovernIB/portafib#617]
> Nos ponemos en contacto para informarles que el próximo 02/11/2021 se impedirá en el entorno de Producción de @firma la remisión de peticiones de forma dinámica (chunked), poniendo así fin al periodo de gracia desde el último aviso realizado el pasado septiembre de 2019 indicando como fecha estimada de fin el pasado 05/11/2019.
> 
> El parámetro en cuestión se encuentra en la cabecera de la petición HTTP con nombre Transfer-Encoding, y con valor "chunked". Este mecanismo envía el cuerpo del mensaje en fragmentos (chunks) lo cual pone en riesgo la seguridad y disponibilidad del servicio.
> A partir de dicha fecha, las peticiones que utilicen dicho mecanismo no serán aceptadas por la Plataforma en el entorno de Producción, devolviendo el error HTTP 411 - Length Required, por lo que les instamos a que realicen la comprobación pertinente en su aplicación (no remitir las peticiones chunked, haciendo uso de la propiedad de cabecera HTTP 'Content-Length'), lo antes posible, para evitar cualquier falta de servicio tras la activación de dicha restricción 

Caldrà deshabilitar-ho al plugin de firma en servidor. Per deshabilitar-ho amb CXF cal afegir la següent línia en configurar el client:

      HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
      // Configurar altres paràmetres, com els timeouts....
      httpClientPolicy.setAllowChunking(false);

      Client client = ClientProxy.getClient(api);
      ((HTTPConduit) client.getConduit()).setClient(httpClientPolicy);

**Comment by anadal-fundaciobit** [comment]
Això es va fer ...
