### ISSUE TITLE
Afegir tests de firma amb passarel·la web

### ISSUE THREAD

**Issue by antonireus** [GovernIB/portafib#619]
Afegir al mòdul creat a #613 un tests de firma amb passarel·la seguint el mateix model que els que ja hi ha emprant l'API de firma simple. Es pot reaprofitar diretmanent tot el que fa referència a la realització de la firma, únicament cal desenvolupar la creació de la petició i la recollida del resultat

**Comment by anadal-fundaciobit** [comment]
L'Api de passarela es deprecarà.
