### ISSUE TITLE
Deprecar l'API REST de Revisors de Firma

### ISSUE THREAD

**Issue by antonireus** [GovernIB/portafib#620]
Aquesta API que permet a una aplicació externa que prèviament ha creat una petició de firma, crear dinàmicament una capsa de REVISOR dins una de les firmes de la petició de firma creada, sempre que aquesta encara no s'hagués iniciat.

Actualment les aplicacions que creen fluxes amb Revisors de Firma, poden crear-los quan creen la petició emprant l'API Simple REST.

Però és possible que aplicacions que emprin l'API antiga amb Web Services SOAP, que no soportaven la creació de Revisors estiguessin emprant aquesta API per una vegada creada la petició de firma amb el Web Service SOAP afegir Revisors a les firmes.

Deprecaríem aquesta API, i quan confirmem que ja no té ús, eliminar-la

**Comment by anadal-fundaciobit** [comment]
Solucionat
