### ISSUE TITLE
Poder definir manualment forma d'extreure NIF de Certificat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#666]
Vist que cada cert temps tenim algun problema amb el tema de l'extracció del NIF d'un Certificat, estaria bé tenir alguna solució ràpida que es pugui definir dins de PortaFIB i solucioni el problema temporalment fins que s'afegeixi el "nou tipus de DNI" a la classe CertificateUtils.
      Estava pensant amb alguna cosa com una llista de properties de camp de certificat on cercar i expressió regular (RegEx) per extreure DNI del camp. Per exemple:
`SERIALNUMBER=^PNOES-([a-zA-Z]?[0-9]{8}[a-zA-Z])$`

El tros de codi que processaria aquesta llista de properties seria alguna cosa com :
import java.util.regex.Pattern;
import java.util.regex.Matcher;
```

public class RegEx {

    public static void main(String[] args) {
        String[] values = new String[] { "PNOES-43096845C", "PNOES-X12345678X", "43096845C" };
        for (String s : values) {
            System.out.println(s + " => " + useRegex(s));
        }
    }

    public static String useRegex(final String input) {
        // Compile regular expression
        final Pattern pattern = Pattern.compile("^PNOES-([a-zA-Z]?[0-9]{8}[a-zA-Z])$",
                Pattern.CASE_INSENSITIVE);
        final Matcher matcher = pattern.matcher(input);
        return matcher.matches()?matcher.group(1):null;
    }
}
```

El resultat de l'execució del programa anterior és:
```
PNOES-43096845C => 43096945C
PNOES-X12345678X => X12345678X
43096945C => null
```

**Comment by areus-fundaciobit** [comment]
Definint una llista d'expressions d'aquest tipus, de manera que la primera que faci "match" retorni el valor, i mentre vagi donant null vagi provant les següents podria ser bastant potent. 

Per la implementació tenir en compte que les instàncies obtingudes amb Pattern.compile es poden reaprofitar, i convé fer-ho ja que és una operació pesada. Veure #570

**Comment by areus-fundaciobit** [comment]
s'ha canviat el sistema perquè es pugui introduir una propietat global per base de dades, `es.caib.portafib.dniPattern` que si està definida s'emprarà per obtenir el DNI

**Comment by areus-fundaciobit** [comment]
s'ha migrat tmabé a 2.1
