### ISSUE TITLE
Pareix que certs numeros de serie excedeixen el tamany de BBDD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#667]
La taula pfi_firma inclou un camp "numeroseriecertificat". La gent de Limit s'ha trobat un cas en que aquest numero de serie es més gran que el que permet la BBDD. 

```
Bon dia,

Durant unes proves de firma amb la validació de firmes activada ens hem trobat amb l'error a continuació. Pareix que s'ha de canviar la precisió del camp numeroseriecertificat, no sé si d'algun camp més.

Per continuar amb les proves he hagut de llevar la precisió del camp numeric.

Es podrà solucionar en una pròxima versió?
```
![nfpbdgceafnplmme](https://user-images.githubusercontent.com/17084256/132504015-079db31b-6057-4974-844c-c096c61605be.png)

**Comment by areus-fundaciobit** [comment]
Els tipus a emprar que són `numeric` en PostgreSQL i `number` en Oracle tenen una precisió indefinida i per tant haurien de poder emmagatzemar qualsevol nombre. El problema ve que a un moment determinat es varen regenerar els scripts de PostgreSQL amb el mòdul `sqlgenerator` i per qualque problema amb el dialecte, aquest camp es va generar com a numeric(19,2).

Cal corregir l'script, i també mirar si es pot solucionar el problema amb el `sqlgenerator`

**Comment by areus-fundaciobit** [comment]
Corregit per la versió 2.0, per la versió 2.1 ha calgut també:
 - GovernIB/genapp/issues/70
