### ISSUE TITLE
Netejar default.css 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#67]
Trac Item: 10 
Trac URL: http://trac.ibit.org/portafib/ticket/10 
Trac Creat: 06/27/13 
"El default.css és una còpia de les propietats css d'un altra projecte i conté moltes classes que no utilitzem. |Revisar aquest document i llevar el que no sigui necessri o s'utilitzi. |Comprovar que tot queda tal igual. "

Teniu en compte que default.css prové de genapp o sigui que estaria bé fer net aquest també.

**Comment by areus-fundaciobit** [comment]
Caldrà tenir en compte també que es visibilitzi adequadament per mòbils
