### ISSUE TITLE
Tamany de Contingut dinàmic al amagar menú

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#697]
Com es pot veure a les captures, quan es minimitza el menú lateral, el contingut es queda al mateix lloc, i el desitjat seria que s'auto ajustes a l'espai alliberat.

![imagen](https://user-images.githubusercontent.com/17084256/138844763-7b3d9d6d-de32-48c5-8d45-d860fd98cb43.png)

![imagen](https://user-images.githubusercontent.com/17084256/138844782-211c9292-5f65-496f-8921-10176b88a619.png)

**Comment by ptrias-fundaciobit** [comment]
Resolt a un issue de GenApp: 

No funciona Amagar menú: 
https://github.com/GovernIB/genapp/issues/79
