### ISSUE TITLE
Eliminació múltiple es permet encara que no hi hagi cap element seleccionat.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#711]
Eliminació múltiple es permet encara que no hi hagi cap element seleccionat.

Trobar solució i aplicar-la a GenApp.

![imagen](https://user-images.githubusercontent.com/17084256/147058986-c0e115f3-7486-4b3d-9a58-0f4f6dcb185c.png)

**Comment by ptrias-fundaciobit** [comment]
Fet i passat a genapp
![image](https://user-images.githubusercontent.com/95921330/198570911-29ddefd8-7a06-4d0d-a459-8a619240d20e.png)
