### ISSUE TITLE
Revisar Totes les opcions del menú Sol·licitant

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#712]
Depèn de "Revisar funcionament PortaFIB 2.2 amb JBoss 7.2 #706"

Seguint amb les revisions de PortaFIB 2.2 (JDK 11 & JBoss 7.2 & BootStrap 4), revisar Totes les opcions del menú Sol·licitant.

**Comment by ptrias-fundaciobit** [comment]
A falta de comprovar documents custodiats, totes les opcions del menu Solicitant van be
