### ISSUE TITLE
Revisar canvi de Idioma en PortaIFB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#719]
Pareix que el canvi d'idioma no funciona en PortaFIB. Adaptar-ho al nou sistema que genera GenApp.

![imagen](https://user-images.githubusercontent.com/17084256/157630988-5cf896d8-535b-4f42-a1d3-def7534ce02a.png)

![imagen](https://user-images.githubusercontent.com/17084256/157631001-ff29513a-9ab9-4139-b8b8-c6323ff58a1a.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat: 
![image](https://user-images.githubusercontent.com/95921330/157660658-297417c0-735e-4d52-8886-d2f870b00463.png)

**Comment by ptrias-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/95921330/157660777-40c40ecd-7672-4c09-8288-98a31020dd29.png)
