### ISSUE TITLE
Revisar alineació del peu de pàgina

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#720]
Actualment GenApp alinea a la dreta i esquerra el peu de pàgina, però PortaIFb no inclou el canvis a peu.jsp. 
(1) Revisar com GenApp actualment aplica els css als components del peu.jsp per a que estiguin alineats
(2) Afegir informació de compilació que també per defecte GenApp aplica al peu.jsp

![imagen](https://user-images.githubusercontent.com/17084256/157631267-ca937697-7dba-4e9e-8631-18f9c4b81d62.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat. Han sortir bastants de problmes per es camí (tiles, preparers, Version, etc)
![image](https://user-images.githubusercontent.com/95921330/158129884-3326dee2-e3b8-44c9-b092-340423ec0a29.png)
