### ISSUE TITLE
No apareix pipella inici però si menú amb un usuari PFI_USER sense entitat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#721]
No apareix pipella inici però si menú amb un usuari PFI_USER sense entitat

![imagen](https://user-images.githubusercontent.com/17084256/157826839-60308652-99dc-49fe-a925-6de8bcb0b372.png)

![imagen](https://user-images.githubusercontent.com/17084256/157826879-8e8a1eb6-9de6-4bc6-aa8e-ff0f596bcee7.png)

**Comment by ptrias-fundaciobit** [comment]
Resolt.
Quan havia un error amb el Plugin de user information, deixava continuar. Ara, llença una excepció.
![image](https://user-images.githubusercontent.com/95921330/160777130-a18449c6-7499-4d69-b103-922553b81529.png)
