### ISSUE TITLE
Fer un trim() en les adreces de correu de plantilles des fluxos de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#723]
He detectado que si dejas un espacio en blanco al final de una dirección de correo de un usuario externo, no deja crearlo por formato incorrecto. Seria interesante hacer un trim() para eliminar espacios en blanco

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/198591360-787bb1f2-ce05-41b4-bce1-8bf2c6f3c82a.png)
