### ISSUE TITLE
Es permet definir revisors en un flux quan aquest no tenen el rol revisor via REST

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#726]
Pareix ser que des de l'API Firma Simple, s'està creant una petició de Firma amb Revisors, on aquests revisors no tenen el rol de revisor.

Fer una comprovació de que els revisors definits dins d'un flux de firma realment tenen el Rol de Revisor, en cas contrari llançar un error.

**Comment by ptrias-fundaciobit** [comment]
Fet!
