### ISSUE TITLE
Revisar els caracters especials en el motiu de rebuig d'una firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#728]
![image](https://user-images.githubusercontent.com/58417501/160388436-99b0c59b-ca85-42db-b9e7-c6135205ac7c.png)

**Comment by ptrias-fundaciobit** [comment]
Fent proves no em surt cap error:
![image](https://user-images.githubusercontent.com/95921330/162434874-1b44ff84-38a8-4d60-81b0-434f0cb47da7.png)

**Comment by anadal-fundaciobit** [comment]
Prova amb Chrome i Firefox ...

**Comment by ptrias-fundaciobit** [comment]
No s'ha pogut reproduir l'error. S'ha provat rebutjar desde diferents navegadors i desde distints usuaris.
![image](https://user-images.githubusercontent.com/95921330/162913210-0cfb85d7-a580-4dca-8c1d-592c4d516a08.png)
