### ISSUE TITLE
Camp "Tipus de Document" de Petició hauria de sortir buit

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#745]
Camp "Tipus de Document" de creació d'una petició de firma hauria d'aparèixer buit i obligar a l'usuari a triar un tipus documental de la llista de tipus documentals. Ara surt per defecte la primera per ordre alfabètic.

**Comment by ptrias-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/95921330/197773555-771ddeba-6399-4229-85de-bd21b37e6611.png)
![image](https://user-images.githubusercontent.com/95921330/197773618-f991488a-c40c-4341-8c7c-678818a1d19a.png)
