### ISSUE TITLE
Camp "Descripció del Tipus de Document" mostrar-se sempre

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#746]
En creació d'una petició de firma el camp "Descripció del Tipus de Document" hauria d'aparèixer sempre com a camp opcional i no només quan tries l'opció "TD99 - Altres tipus de documents" del camp "Tipus de document". A vegades interessa posar una descripció del tipus de document. Per exemple el "TD17 - Recurs", pot ser un recurs contenciós-administratiu, un recurs d'alçada, un recurs extraordinari de revisió o un recurs potestatiu de reposició i estaria bé poder-ho posar en aquest camp.

Podria millorar-se amb una propietat que permeti el comportament actual o aquest nou comportament.

Avisar a APB quan estigui fet.

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/197179833-0ac04fe8-fdc2-46a8-a3d1-ecfc16e88bc7.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglar que era funciona per propietat de BBDD de l'entitat

**Comment by ptrias-fundaciobit** [comment]
Actualitzat script d'update
