### ISSUE TITLE
Canvi de icones "icon-" per awesome

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#751]
Dins del Back de PortaFIB 2.2. encara queden moltes de icones del tipus "icon-????" de Glyphicons (https://getbootstrap.com/2.3.2/base-css.html#icons).
S'han de cercar i substituir per icones FONTAWESOME (https://fontawesome.com/v5/search)

NOTA: icon-white s'ha de deixar i no s'ha de substituir per res.

Procés:
(1) Fer cerca dins portafib-back de "icon-XXXX"
(2) Triar el primer que surti (per exemple icon-list-alt)
(3) Anar a https://getbootstrap.com/2.3.2/base-css.html#icons i cercar el dibuix de la icona
(4) Anar a https://fontawesome.com/v5/search i cercar una icona similar: s'ha de cercar per "solid" i "free". Per exemple "fas fa-list-alt"
(5) Cercar en el codi de PortaFIB totes les endades del punt (2) i substituir-les per la trobada en el punt (4).

**Comment by ptrias-fundaciobit** [comment]
Fet: 
![image](https://user-images.githubusercontent.com/95921330/191255091-b7947bff-d2ed-4ed9-bece-29b6457b1224.png)
