### ISSUE TITLE
Flux antic amb càrrec apareix carrec actual.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#753]
Enviat per l'APB:

Aquest flux és de fa 2 anys i el President era en una altre persona. Ara fa uns mesos varem posar en Santiago Mayol i el flux antic ens surt com que el va firmar ell.

![imatge](https://user-images.githubusercontent.com/17084256/190978968-93cc68f5-818a-4643-a6e0-ac54f837dc08.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
Abans d'enviar, agafa el nom del qui ocupa el carrec, després, aafa el nom de a qui l'hi ha enviat (a partir de l'estat de firma que está requerit per firmar)
