### ISSUE TITLE
Millores en fitxers de Traduccions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#755]
Aplicar la millora descrita en aquest ISSUE https://github.com/Fundacio-Bit/enviafib/issues/211 a PORTAFIB:  revisar el darrer parxe aplicat.

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/191254651-d513678a-9d7d-48df-a789-7bc7d3fff4ea.png)
