### ISSUE TITLE
Fer proves, casos d'us, i provocar errors per enviar peticions a PôrtaFIB via WS

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#759]
Des de la DGMAD ens comenten que els  WS de RegWEb amb JBoss 7.2 funcionen, excepte en el cas d'error, que els WS no funcionen.
Revisar si passa el mateix a PortaFIB.

(1) Provar exemple amb portafib2.fundaciobit.org.
(2) Provar exemple amb localhost.
(3) Provocar error a servidor i revisar que el mateix error arriba al client.

**Comment by ptrias-fundaciobit** [comment]
Provar i revisat. Els errors que es produeixen al servidor, son els mateixos que arriven al client.
