### ISSUE TITLE
Error cancel·lant creació d'una entitat

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [GovernIB/portafib#761]
Error cancelant creació d'una entitat
![image](https://user-images.githubusercontent.com/95921330/196944569-e5e35fc1-502b-4e0c-a775-ea2dc822aade.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat. Afegir ISSUE a genApp per solucionar-ho d'arrel: https://github.com/GovernIB/genapp/issues/148
