### ISSUE TITLE
Fer que un PDF Certificat es pugui signar

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#764]
Des de l'APB el dia 16/12/2022, 13:44 va enviar una consulta al compte de correu de firma de Govern Digital  amb un document PDF signat i certificat adjunt. Comentaven que al intentar signar  de nou amb Autofirma sortia el següent error:

![imatge](https://user-images.githubusercontent.com/17084256/208369705-f40138d4-f530-4234-ba01-8cbb2344ed30.png)

Pareix ser que un document PDF signat i certificat no es pot tornar a signar. He fet la prova de signar-ho directament des de Windows 10 amb Autofirma i aquest és l'error que apareix:

![imatge](https://user-images.githubusercontent.com/17084256/208367274-568ad998-495c-4fac-ac51-6f18d8ae5c92.png)

En aquest issue és descriu el Problema: https://github.com/ctt-gob-es/clienteafirma/issues/21

Fer que  el plugin de AutoFirma accepti signar documents PDF-Certificats: això es fa afegint el següent extraParameter "allowSigningCertifiedPdfs" amb valor "true". (En la següent captura es marca on afegir aquesta propietat)

![imatge](https://user-images.githubusercontent.com/17084256/208373771-607976b8-7c50-4037-a003-3eab2599a775.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat

**Comment by ptrias-fundaciobit** [comment]
[ddb1b40da2ace2f08ee69461d2083da95329fc1f](https://github.com/GovernIB/pluginsib-signatureweb/commit/ddb1b40da2ace2f08ee69461d2083da95329fc1f)

**Comment by anadal-fundaciobit** [comment]
Per versió 2.0.

![imatge](https://user-images.githubusercontent.com/17084256/209075692-29814420-4e1e-4c77-81f2-6cc6a44193e5.png)

**Comment by anadal-fundaciobit** [comment]
El problema és mes greu del que me pensava i en principi la solució no està en el nostre codi ...

      Pareix ser que els supergenis de Madrid han ficat codi de mostrar diàlegs de confirmació en el codi de servidor. :-(  
  
     Jo vaig provar la modificació en el meu servidor (el meu ordinador) i la cosa va funcionar. Avui, he copiat l'ear al servidor (linux) de la DEMO de portafib i no m'ha funcionat (mateix ear, mateix navegador i mateix Autofirma però m'ha mostrat l'error que vares enviar). Com pot ser ???? Resulta que com he dit abans encara que indiquis que permets firmes de PDFs amb Certificats, la llibreria (jar) que es troba en el servidor intenta obrir un diàleg gràfic per demanar a l'usuari si realment vol signar un PDF's amb Certificat. Com el servidor és un linux sense UI gràfica llança una excepció que fa que el procés de firma falli.

     El problema es que totes aquestes classes  estan dins llibreries de afirma:
    at es.gob.afirma.core.ui.AOUIFactory.showConfirmDialog(AOUIFactory.java:157)
    at es.gob.afirma.signers.pades.PdfUtil.checkPdfCertification(PdfUtil.java:179)
    at es.gob.afirma.signers.pades.PdfSessionManager.getSessionData(PdfSessionManager.java:158)
    at es.gob.afirma.signers.pades.PAdESTriPhaseSigner.preSign(PAdESTriPhaseSigner.java:180)


![imatge](https://user-images.githubusercontent.com/17084256/214003610-ad4561ae-7e20-4c7a-a792-a27c6671813b.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
