### ISSUE TITLE
Applet no funciona amb https 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#79]
Trac Item: 185 
Trac URL: http://trac.ibit.org/portafib/ticket/185 
Trac Creat: 01/09/14
"Quan s'estableix una connexió de tipus https l'applet no pot establir connexió amb el servidor. Pareix que cerca entre tots els certificats dels sistema quin és el que accepta el jboss. |Actualment hi ha un parxe que quan estem connectats via https, per descarregar els jars i el documents, es connecta a la web via http. L'inconvenient d'aquest sistema és que t'apareix un popup demanat l'usuari i contrasenya. "

**Comment by areus-fundaciobit** [comment]
issue obsoleta
