### ISSUE TITLE
Afegir informació de l'usuari creador d'una plantilla de flux de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#800]
Si es crea una plantilla de flux de firma des d'una aplicació externa, el camp "Propietat de " fa referència a l'aplicació que l'ha creada (usuari d'integració), però no hi ha cap referència a l'usuari persona. S'hauria d'afegir un nou camp per poder registrar la persona que crea el flux i no només l'aplicació. Actualment, des de RIPEA utilitzam el camp "Descripció" amb valor "user=uXXXX" però seria millor fer-ho amb un camp específic.

**Comment by anadal-fundaciobit** [comment]
![imatge](https://github.com/GovernIB/portafib/assets/17084256/1414cd4e-c26b-407d-874f-26863d385227)
