### ISSUE TITLE
Normalitzar els fitxers de propietats per adaptar-los als estàndards de desenvolupament de la CAIB

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#837]
El fitxer portafib.system.properties només ha d'incloure propietats de tipus endpoit, usuari, contrasenya i path en filesystem. La resta de propietats s'han de moure al fitxer portafib.properties d'acord amb els estàndards de desenvolupament del Govern. Aquestes darreres propietats també es podem gestionar des del backoffice (mai les propietats del portafib.system.properties).

**Comment by anadal-fundaciobit** [comment]
En conversa amb @acuevas-dgtic  s'ha decidit moure totes les propietats del Plugin de UserInformation a protafib.system.properties ja que són dades que només ha de modificar la gent de Sistemes, que són els coneixedors dels sistemes d'Autenticació i Autorització.
Solucionat. !!!!
