### ISSUE TITLE
Error llegint dades de UserInformation per nous usuaris

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [GovernIB/portafib#872]
A la classe AuthenticationSuccessListener no es té en compte que algunes dades venen com a strings buids, i les comprovacions de si son nulls no filtren correctament aquestes dades.

S'ha d'incloure una comprovació extra especialment al camp del email, per filtrar si l'String es null o buit.

**Comment by anadal-fundaciobit** [comment]
S'ha intentat que quan el plugin de userinformation no torni email, es vaig a una pàgina d'edició i l'usuari l'introdueix, però l'usuari podria tancar el navegador i tornar entrar i es quedaria amb un email incorrecte.

![Image](https://github.com/user-attachments/assets/acd995d4-f8b3-4796-8a4f-98abcc93245f)
