### ISSUE TITLE
Amagar les dades de compilació als usuaris finals

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/portafib#902]
Les dades que apareixen al peu de pàgina haurien d'estar visibles només per als administradors.

```
Build: 2024-10-15T11:46:31Z
JDK: 11.0.23+9
Versió de JBoss Compatible: 7.2.0.GA
Versió de JBoss Executant-se: 7.2.0.GA
Revisió: 077e8e18
```

**Comment by acuevas-dgtic** [comment]
Com a molt, el número de versió, pero no el JDK ni el Jboss

**Comment by anadal-fundaciobit** [comment]
![Image](https://github.com/user-attachments/assets/afc9c55d-b411-477c-8fc3-3eb627197b16)

**Comment by anadal-fundaciobit** [comment]
Solucionat
