### ISSUE TITLE
 Problemes a l'hora de crear i modificar fluxos de firma en un tipus de document

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#903]
Ve del Issue  Problemes a l'hora de crear i modificar fluxos de firma en un tipus de document re ripea (VEUIRE https://github.com/GovernIB/ripea/issues/1552)

**Comment by anadal-fundaciobit** [comment]
Dia 18/11/2024 enviat correu a Asier indicant que això ja està solucionat des de la versió 3.0.1

**Comment by acuevas-dgtic** [comment]
Pareix resolt
